<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Webhooks;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class AttemptResponse
{
    /**
     *
     * @var Attempt $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Webhooks\Attempt')]
    public Attempt $data;

    /**
     * @param  Attempt  $data
     * @phpstan-pure
     */
    public function __construct(Attempt $data)
    {
        $this->data = $data;
    }
}