<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Webhooks;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class Cursor
{
    /**
     * $data
     *
     * @var array<WebhooksConfig> $data
     */
    #[SerializedName('data')]
    #[Type('array<\formance\stack\Models\Webhooks\WebhooksConfig>')]
    public array $data;

    /**
     *
     * @var bool $hasMore
     */
    #[SerializedName('hasMore')]
    public bool $hasMore;

    /**
     * @param  array<WebhooksConfig>  $data
     * @param  bool  $hasMore
     * @phpstan-pure
     */
    public function __construct(array $data, bool $hasMore)
    {
        $this->data = $data;
        $this->hasMore = $hasMore;
    }
}