<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Wallets;


class Balances
{
    /**
     *
     * @var AssetHolder $assetHolder
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('main')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Wallets\AssetHolder')]
    public AssetHolder $assetHolder;

    /**
     * @param  AssetHolder  $assetHolder
     * @phpstan-pure
     */
    public function __construct(AssetHolder $assetHolder)
    {
        $this->assetHolder = $assetHolder;
    }
}