<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Wallets;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class CreateBalanceResponse
{
    /**
     *
     * @var Balance $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Wallets\Balance')]
    public Balance $data;

    /**
     * @param  Balance  $data
     * @phpstan-pure
     */
    public function __construct(Balance $data)
    {
        $this->data = $data;
    }
}