<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Wallets;


class CreateBalanceResponse
{
    /**
     *
     * @var Balance $balance
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Wallets\Balance')]
    public Balance $balance;

    /**
     * @param  Balance  $balance
     * @phpstan-pure
     */
    public function __construct(Balance $balance)
    {
        $this->balance = $balance;
    }
}