<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Wallets;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class GetBalanceResponse
{
    /**
     *
     * @var BalanceWithAssets $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Wallets\BalanceWithAssets')]
    public BalanceWithAssets $data;

    /**
     * @param  BalanceWithAssets  $data
     * @phpstan-pure
     */
    public function __construct(BalanceWithAssets $data)
    {
        $this->data = $data;
    }
}