<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Errors;

use formance\stack\Models\Shared;
/** PaymentsErrorResponse - Error */
class PaymentsErrorResponse
{
    /**
     *
     * @var Shared\PaymentsErrorsEnum $errorCode
     */
    #[\JMS\Serializer\Annotation\SerializedName('errorCode')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\PaymentsErrorsEnum')]
    public Shared\PaymentsErrorsEnum $errorCode;

    /**
     *
     * @var string $errorMessage
     */
    #[\JMS\Serializer\Annotation\SerializedName('errorMessage')]
    public string $errorMessage;

    /**
     * @param  ?Shared\PaymentsErrorsEnum  $errorCode
     * @param  ?string  $errorMessage
     */
    public function __construct(?Shared\PaymentsErrorsEnum $errorCode = null, ?string $errorMessage = null)
    {
        $this->errorCode = $errorCode;
        $this->errorMessage = $errorMessage;
    }
}