<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Errors;

class V2ErrorThrowable extends \RuntimeException
{
    public V2Error $container;

    public function __construct(string $message, int $statusCode, V2Error $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}