<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Reconciliation;

use formance\stack\Utils;
/** ErrorResponse - Error response */
class ErrorResponse
{
    /**
     *
     * @var ?string $details
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('details')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $details = null;

    /**
     *
     * @var string $errorCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errorCode')]
    public string $errorCode;

    /**
     *
     * @var string $errorMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errorMessage')]
    public string $errorMessage;

    /**
     * @param  string  $errorCode
     * @param  string  $errorMessage
     * @param  ?string  $details
     * @phpstan-pure
     */
    public function __construct(string $errorCode, string $errorMessage, ?string $details = null)
    {
        $this->details = $details;
        $this->errorCode = $errorCode;
        $this->errorMessage = $errorMessage;
    }

    public function toException(): ErrorResponseThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ErrorResponseThrowable($message, (int) $code, $this);
    }
}