<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Reconciliation;


/** EvaluationsCursorResponse - OK */
class EvaluationsCursorResponse
{
    /**
     *
     * @var \formance\stack\Models\Reconciliation\EvaluationsCursorResponseCursor $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Reconciliation\EvaluationsCursorResponseCursor')]
    public EvaluationsCursorResponseCursor $cursor;

    /**
     * @param  \formance\stack\Models\Reconciliation\EvaluationsCursorResponseCursor  $cursor
     * @phpstan-pure
     */
    public function __construct(EvaluationsCursorResponseCursor $cursor)
    {
        $this->cursor = $cursor;
    }
}