<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Reconciliation;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class PolicyRequest
{
    /**
     *
     * @var string $ledgerName
     */
    #[SerializedName('ledgerName')]
    public string $ledgerName;

    /**
     * $ledgerQuery
     *
     * @var array<string, mixed> $ledgerQuery
     */
    #[SerializedName('ledgerQuery')]
    #[Type('array<string, mixed>')]
    public array $ledgerQuery;

    /**
     *
     * @var string $name
     */
    #[SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $paymentsPoolID
     */
    #[SerializedName('paymentsPoolID')]
    public string $paymentsPoolID;

    /**
     * @param  string  $ledgerName
     * @param  array<string, mixed>  $ledgerQuery
     * @param  string  $name
     * @param  string  $paymentsPoolID
     * @phpstan-pure
     */
    public function __construct(string $ledgerName, array $ledgerQuery, string $name, string $paymentsPoolID)
    {
        $this->ledgerName = $ledgerName;
        $this->ledgerQuery = $ledgerQuery;
        $this->name = $name;
        $this->paymentsPoolID = $paymentsPoolID;
    }
}