<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Reconciliation;


/** PoliciesCursorResponse - OK */
class PoliciesCursorResponse
{
    /**
     *
     * @var \formance\stack\Models\Reconciliation\PoliciesCursorResponseCursor $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Reconciliation\PoliciesCursorResponseCursor')]
    public PoliciesCursorResponseCursor $cursor;

    /**
     * @param  \formance\stack\Models\Reconciliation\PoliciesCursorResponseCursor  $cursor
     * @phpstan-pure
     */
    public function __construct(PoliciesCursorResponseCursor $cursor)
    {
        $this->cursor = $cursor;
    }
}