<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Reconciliation;
use Speakeasy\Serializer\Annotation\SerializedName;


class ReconciliationRequest
{
    /**
     *
     * @var \DateTime $reconciledAtLedger
     */
    #[SerializedName('reconciledAtLedger')]
    public \DateTime $reconciledAtLedger;

    /**
     *
     * @var \DateTime $reconciledAtPayments
     */
    #[SerializedName('reconciledAtPayments')]
    public \DateTime $reconciledAtPayments;

    /**
     * @param  \DateTime  $reconciledAtLedger
     * @param  \DateTime  $reconciledAtPayments
     * @phpstan-pure
     */
    public function __construct(\DateTime $reconciledAtLedger, \DateTime $reconciledAtPayments)
    {
        $this->reconciledAtLedger = $reconciledAtLedger;
        $this->reconciledAtPayments = $reconciledAtPayments;
    }
}