<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;


class GetWorkflowInstanceHistoryResponse
{
    /**
     * $workflowInstanceHistoryList
     *
     * @var array<WorkflowInstanceHistory> $workflowInstanceHistoryList
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\formance\stack\Models\Orchestration\WorkflowInstanceHistory>')]
    public array $workflowInstanceHistoryList;

    /**
     * @param  array<WorkflowInstanceHistory>  $workflowInstanceHistoryList
     * @phpstan-pure
     */
    public function __construct(array $workflowInstanceHistoryList)
    {
        $this->workflowInstanceHistoryList = $workflowInstanceHistoryList;
    }
}