<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;


class V2ActivityCreditWallet
{
    /**
     *
     * @var ?\formance\stack\Models\Orchestration\V2CreditWalletRequest $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Orchestration\V2CreditWalletRequest|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V2CreditWalletRequest $data = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * @param  ?\formance\stack\Models\Orchestration\V2CreditWalletRequest  $data
     * @param  ?string  $id
     * @phpstan-pure
     */
    public function __construct(?V2CreditWalletRequest $data = null, ?string $id = null)
    {
        $this->data = $data;
        $this->id = $id;
    }
}