<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class V2DebitWalletRequest
{
    /**
     *
     * @var V2Monetary $amount
     */
    #[SerializedName('amount')]
    #[Type('\formance\stack\Models\Orchestration\V2Monetary')]
    public V2Monetary $amount;

    /**
     * Metadata associated with the wallet.
     *
     * @var array<string, string> $metadata
     */
    #[SerializedName('metadata')]
    #[Type('array<string, string>')]
    public array $metadata;

    /**
     * $balances
     *
     * @var ?array<string> $balances
     */
    #[SerializedName('balances')]
    #[Type('array<string>|null')]
    #[SkipWhenNull]
    public ?array $balances = null;

    /**
     *
     * @var ?string $description
     */
    #[SerializedName('description')]
    #[SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var V2LedgerAccountSubject|V2WalletSubject|null $destination
     */
    #[SerializedName('destination')]
    #[Type('\formance\stack\Models\Orchestration\V2LedgerAccountSubject|\formance\stack\Models\Orchestration\V2WalletSubject|null')]
    #[SkipWhenNull]
    public V2LedgerAccountSubject|V2WalletSubject|null $destination = null;

    /**
     * Set to true to create a pending hold. If false, the wallet will be debited immediately.
     *
     * @var ?bool $pending
     */
    #[SerializedName('pending')]
    #[SkipWhenNull]
    public ?bool $pending = null;

    /**
     * cannot be used in conjunction with `pending` property
     *
     * @var ?\DateTime $timestamp
     */
    #[SerializedName('timestamp')]
    #[SkipWhenNull]
    public ?\DateTime $timestamp = null;

    /**
     * @param  V2Monetary  $amount
     * @param  array<string, string>  $metadata
     * @param  ?array<string>  $balances
     * @param  ?string  $description
     * @param  V2LedgerAccountSubject|V2WalletSubject|null  $destination
     * @param  ?bool  $pending
     * @param  ?\DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(V2Monetary $amount, array $metadata, ?array $balances = null, ?string $description = null, V2LedgerAccountSubject|V2WalletSubject|null $destination = null, ?bool $pending = null, ?\DateTime $timestamp = null)
    {
        $this->amount = $amount;
        $this->metadata = $metadata;
        $this->balances = $balances;
        $this->description = $description;
        $this->destination = $destination;
        $this->pending = $pending;
        $this->timestamp = $timestamp;
    }
}