<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;


class V2DebitWalletRequest
{
    /**
     *
     * @var V2Monetary $v2Monetary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Orchestration\V2Monetary')]
    public V2Monetary $v2Monetary;

    /**
     * Metadata associated with the wallet.
     *
     * @var array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>')]
    public array $metadata;

    /**
     *
     * @var V2LedgerAccountSubject|V2WalletSubject|null $v2Subject
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Orchestration\V2LedgerAccountSubject|\formance\stack\Models\Orchestration\V2WalletSubject|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public V2LedgerAccountSubject|V2WalletSubject|null $v2Subject = null;

    /**
     * $balances
     *
     * @var ?array<string> $balances
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('balances')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $balances = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Set to true to create a pending hold. If false, the wallet will be debited immediately.
     *
     * @var ?bool $pending
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pending')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $pending = null;

    /**
     * cannot be used in conjunction with `pending` property
     *
     * @var ?\DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $timestamp = null;

    /**
     * @param  V2Monetary  $v2Monetary
     * @param  array<string, string>  $metadata
     * @param  V2LedgerAccountSubject|V2WalletSubject|null  $v2Subject
     * @param  ?array<string>  $balances
     * @param  ?string  $description
     * @param  ?bool  $pending
     * @param  ?\DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(V2Monetary $v2Monetary, array $metadata, V2LedgerAccountSubject|V2WalletSubject|null $v2Subject = null, ?array $balances = null, ?string $description = null, ?bool $pending = null, ?\DateTime $timestamp = null)
    {
        $this->v2Monetary = $v2Monetary;
        $this->metadata = $metadata;
        $this->v2Subject = $v2Subject;
        $this->balances = $balances;
        $this->description = $description;
        $this->pending = $pending;
        $this->timestamp = $timestamp;
    }
}