<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;


class V2DebitWalletResponse
{
    /**
     *
     * @var \formance\stack\Models\Orchestration\V2Hold $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Orchestration\V2Hold')]
    public V2Hold $data;

    /**
     * @param  \formance\stack\Models\Orchestration\V2Hold  $data
     * @phpstan-pure
     */
    public function __construct(V2Hold $data)
    {
        $this->data = $data;
    }
}