<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class V2GetWalletResponse
{
    /**
     *
     * @var V2WalletWithBalances $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Orchestration\V2WalletWithBalances')]
    public V2WalletWithBalances $data;

    /**
     * @param  V2WalletWithBalances  $data
     * @phpstan-pure
     */
    public function __construct(V2WalletWithBalances $data)
    {
        $this->data = $data;
    }
}