<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class V2ListWorkflowsResponse
{
    /**
     *
     * @var V2ListWorkflowsResponseCursor $cursor
     */
    #[SerializedName('cursor')]
    #[Type('\formance\stack\Models\Orchestration\V2ListWorkflowsResponseCursor')]
    public V2ListWorkflowsResponseCursor $cursor;

    /**
     * @param  V2ListWorkflowsResponseCursor  $cursor
     * @phpstan-pure
     */
    public function __construct(V2ListWorkflowsResponseCursor $cursor)
    {
        $this->cursor = $cursor;
    }
}