<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;


class V2PaymentResponse
{
    /**
     *
     * @var V2Payment $v2Payment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Orchestration\V2Payment')]
    public V2Payment $v2Payment;

    /**
     * @param  V2Payment  $v2Payment
     * @phpstan-pure
     */
    public function __construct(V2Payment $v2Payment)
    {
        $this->v2Payment = $v2Payment;
    }
}