<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class V2PostTransaction
{
    /**
     * $metadata
     *
     * @var array<string, string> $metadata
     */
    #[SerializedName('metadata')]
    #[Type('array<string, string>')]
    public array $metadata;

    /**
     * $postings
     *
     * @var ?array<V2Posting> $postings
     */
    #[SerializedName('postings')]
    #[Type('array<\formance\stack\Models\Orchestration\V2Posting>|null')]
    #[SkipWhenNull]
    public ?array $postings = null;

    /**
     *
     * @var ?string $reference
     */
    #[SerializedName('reference')]
    #[SkipWhenNull]
    public ?string $reference = null;

    /**
     *
     * @var ?V2PostTransactionScript $script
     */
    #[SerializedName('script')]
    #[Type('\formance\stack\Models\Orchestration\V2PostTransactionScript|null')]
    #[SkipWhenNull]
    public ?V2PostTransactionScript $script = null;

    /**
     *
     * @var ?\DateTime $timestamp
     */
    #[SerializedName('timestamp')]
    #[SkipWhenNull]
    public ?\DateTime $timestamp = null;

    /**
     * @param  array<string, string>  $metadata
     * @param  ?array<V2Posting>  $postings
     * @param  ?string  $reference
     * @param  ?V2PostTransactionScript  $script
     * @param  ?\DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(array $metadata, ?array $postings = null, ?string $reference = null, ?V2PostTransactionScript $script = null, ?\DateTime $timestamp = null)
    {
        $this->metadata = $metadata;
        $this->postings = $postings;
        $this->reference = $reference;
        $this->script = $script;
        $this->timestamp = $timestamp;
    }
}