<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;


class V2Transaction
{
    /**
     * $v2Metadata
     *
     * @var array<string, string> $v2Metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>')]
    public array $v2Metadata;

    /**
     * $postings
     *
     * @var array<V2Posting> $postings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postings')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\formance\stack\Models\Orchestration\V2Posting>')]
    public array $postings;

    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var \Brick\Math\BigInteger $txid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('txid')]
    public \Brick\Math\BigInteger $txid;

    /**
     *
     * @var ?string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reference = null;

    /**
     * @param  array<string, string>  $v2Metadata
     * @param  array<V2Posting>  $postings
     * @param  \DateTime  $timestamp
     * @param  \Brick\Math\BigInteger  $txid
     * @param  ?string  $reference
     * @phpstan-pure
     */
    public function __construct(array $v2Metadata, array $postings, \DateTime $timestamp, \Brick\Math\BigInteger $txid, ?string $reference = null)
    {
        $this->v2Metadata = $v2Metadata;
        $this->postings = $postings;
        $this->timestamp = $timestamp;
        $this->txid = $txid;
        $this->reference = $reference;
    }
}