<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class V2Update
{
    /**
     *
     * @var ?V2UpdateAccount $account
     */
    #[SerializedName('account')]
    #[Type('\formance\stack\Models\Orchestration\V2UpdateAccount|null')]
    #[SkipWhenNull]
    public ?V2UpdateAccount $account = null;

    /**
     * @param  ?V2UpdateAccount  $account
     * @phpstan-pure
     */
    public function __construct(?V2UpdateAccount $account = null)
    {
        $this->account = $account;
    }
}