<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Orchestration;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class WorkflowInstanceHistoryStageInput
{
    /**
     *
     * @var ?ActivityAddAccountMetadata $addAccountMetadata
     */
    #[SerializedName('AddAccountMetadata')]
    #[Type('\formance\stack\Models\Orchestration\ActivityAddAccountMetadata|null')]
    #[SkipWhenNull]
    public ?ActivityAddAccountMetadata $addAccountMetadata = null;

    /**
     *
     * @var ?ActivityConfirmHold $confirmHold
     */
    #[SerializedName('ConfirmHold')]
    #[Type('\formance\stack\Models\Orchestration\ActivityConfirmHold|null')]
    #[SkipWhenNull]
    public ?ActivityConfirmHold $confirmHold = null;

    /**
     *
     * @var ?ActivityCreateTransaction $createTransaction
     */
    #[SerializedName('CreateTransaction')]
    #[Type('\formance\stack\Models\Orchestration\ActivityCreateTransaction|null')]
    #[SkipWhenNull]
    public ?ActivityCreateTransaction $createTransaction = null;

    /**
     *
     * @var ?CreateTransferInitiationRequest $createTransferInitiation
     */
    #[SerializedName('CreateTransferInitiation')]
    #[Type('\formance\stack\Models\Orchestration\CreateTransferInitiationRequest|null')]
    #[SkipWhenNull]
    public ?CreateTransferInitiationRequest $createTransferInitiation = null;

    /**
     *
     * @var ?ActivityCreditWallet $creditWallet
     */
    #[SerializedName('CreditWallet')]
    #[Type('\formance\stack\Models\Orchestration\ActivityCreditWallet|null')]
    #[SkipWhenNull]
    public ?ActivityCreditWallet $creditWallet = null;

    /**
     *
     * @var ?ActivityDebitWallet $debitWallet
     */
    #[SerializedName('DebitWallet')]
    #[Type('\formance\stack\Models\Orchestration\ActivityDebitWallet|null')]
    #[SkipWhenNull]
    public ?ActivityDebitWallet $debitWallet = null;

    /**
     *
     * @var ?ActivityGetAccount $getAccount
     */
    #[SerializedName('GetAccount')]
    #[Type('\formance\stack\Models\Orchestration\ActivityGetAccount|null')]
    #[SkipWhenNull]
    public ?ActivityGetAccount $getAccount = null;

    /**
     *
     * @var ?ActivityGetPayment $getPayment
     */
    #[SerializedName('GetPayment')]
    #[Type('\formance\stack\Models\Orchestration\ActivityGetPayment|null')]
    #[SkipWhenNull]
    public ?ActivityGetPayment $getPayment = null;

    /**
     *
     * @var ?ActivityGetWallet $getWallet
     */
    #[SerializedName('GetWallet')]
    #[Type('\formance\stack\Models\Orchestration\ActivityGetWallet|null')]
    #[SkipWhenNull]
    public ?ActivityGetWallet $getWallet = null;

    /**
     *
     * @var ?ActivityListWallets $listWallets
     */
    #[SerializedName('ListWallets')]
    #[Type('\formance\stack\Models\Orchestration\ActivityListWallets|null')]
    #[SkipWhenNull]
    public ?ActivityListWallets $listWallets = null;

    /**
     *
     * @var ?ActivityRevertTransaction $revertTransaction
     */
    #[SerializedName('RevertTransaction')]
    #[Type('\formance\stack\Models\Orchestration\ActivityRevertTransaction|null')]
    #[SkipWhenNull]
    public ?ActivityRevertTransaction $revertTransaction = null;

    /**
     *
     * @var ?StripeTransferRequest $stripeTransfer
     */
    #[SerializedName('StripeTransfer')]
    #[Type('\formance\stack\Models\Orchestration\StripeTransferRequest|null')]
    #[SkipWhenNull]
    public ?StripeTransferRequest $stripeTransfer = null;

    /**
     *
     * @var ?ActivityVoidHold $voidHold
     */
    #[SerializedName('VoidHold')]
    #[Type('\formance\stack\Models\Orchestration\ActivityVoidHold|null')]
    #[SkipWhenNull]
    public ?ActivityVoidHold $voidHold = null;

    /**
     * @param  ?ActivityAddAccountMetadata  $addAccountMetadata
     * @param  ?ActivityConfirmHold  $confirmHold
     * @param  ?ActivityCreateTransaction  $createTransaction
     * @param  ?CreateTransferInitiationRequest  $createTransferInitiation
     * @param  ?ActivityCreditWallet  $creditWallet
     * @param  ?ActivityDebitWallet  $debitWallet
     * @param  ?ActivityGetAccount  $getAccount
     * @param  ?ActivityGetPayment  $getPayment
     * @param  ?ActivityGetWallet  $getWallet
     * @param  ?ActivityListWallets  $listWallets
     * @param  ?ActivityRevertTransaction  $revertTransaction
     * @param  ?StripeTransferRequest  $stripeTransfer
     * @param  ?ActivityVoidHold  $voidHold
     * @phpstan-pure
     */
    public function __construct(?ActivityAddAccountMetadata $addAccountMetadata = null, ?ActivityConfirmHold $confirmHold = null, ?ActivityCreateTransaction $createTransaction = null, ?CreateTransferInitiationRequest $createTransferInitiation = null, ?ActivityCreditWallet $creditWallet = null, ?ActivityDebitWallet $debitWallet = null, ?ActivityGetAccount $getAccount = null, ?ActivityGetPayment $getPayment = null, ?ActivityGetWallet $getWallet = null, ?ActivityListWallets $listWallets = null, ?ActivityRevertTransaction $revertTransaction = null, ?StripeTransferRequest $stripeTransfer = null, ?ActivityVoidHold $voidHold = null)
    {
        $this->addAccountMetadata = $addAccountMetadata;
        $this->confirmHold = $confirmHold;
        $this->createTransaction = $createTransaction;
        $this->createTransferInitiation = $createTransferInitiation;
        $this->creditWallet = $creditWallet;
        $this->debitWallet = $debitWallet;
        $this->getAccount = $getAccount;
        $this->getPayment = $getPayment;
        $this->getWallet = $getWallet;
        $this->listWallets = $listWallets;
        $this->revertTransaction = $revertTransaction;
        $this->stripeTransfer = $stripeTransfer;
        $this->voidHold = $voidHold;
    }
}