<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;


class AccountResponse
{
    /**
     *
     * @var AccountWithVolumesAndBalances $accountWithVolumesAndBalances
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Ledger\AccountWithVolumesAndBalances')]
    public AccountWithVolumesAndBalances $accountWithVolumesAndBalances;

    /**
     * @param  AccountWithVolumesAndBalances  $accountWithVolumesAndBalances
     * @phpstan-pure
     */
    public function __construct(AccountWithVolumesAndBalances $accountWithVolumesAndBalances)
    {
        $this->accountWithVolumesAndBalances = $accountWithVolumesAndBalances;
    }
}