<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;


class BalancesCursorResponse
{
    /**
     *
     * @var \formance\stack\Models\Ledger\BalancesCursorResponseCursor $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Ledger\BalancesCursorResponseCursor')]
    public BalancesCursorResponseCursor $cursor;

    /**
     * @param  \formance\stack\Models\Ledger\BalancesCursorResponseCursor  $cursor
     * @phpstan-pure
     */
    public function __construct(BalancesCursorResponseCursor $cursor)
    {
        $this->cursor = $cursor;
    }
}