<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class ConfigInfoResponse
{
    /**
     *
     * @var ConfigInfo $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Ledger\ConfigInfo')]
    public ConfigInfo $data;

    /**
     * @param  ConfigInfo  $data
     * @phpstan-pure
     */
    public function __construct(ConfigInfo $data)
    {
        $this->data = $data;
    }
}