<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Brick\Math\BigInteger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class Transaction
{
    /**
     * $postings
     *
     * @var array<Posting> $postings
     */
    #[SerializedName('postings')]
    #[Type('array<\formance\stack\Models\Ledger\Posting>')]
    public array $postings;

    /**
     *
     * @var \DateTime $timestamp
     */
    #[SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var BigInteger $txid
     */
    #[SerializedName('txid')]
    public BigInteger $txid;

    /**
     * $postCommitVolumes
     *
     * @var ?array<string, array<string, Volume>> $postCommitVolumes
     */
    #[SerializedName('postCommitVolumes')]
    #[Type('array<string, array<string, \formance\stack\Models\Ledger\Volume>>|null')]
    #[SkipWhenNull]
    public ?array $postCommitVolumes = null;

    /**
     * $preCommitVolumes
     *
     * @var ?array<string, array<string, Volume>> $preCommitVolumes
     */
    #[SerializedName('preCommitVolumes')]
    #[Type('array<string, array<string, \formance\stack\Models\Ledger\Volume>>|null')]
    #[SkipWhenNull]
    public ?array $preCommitVolumes = null;

    /**
     *
     * @var ?string $reference
     */
    #[SerializedName('reference')]
    #[SkipWhenNull]
    public ?string $reference = null;

    /**
     * $metadata
     *
     * @var ?array<string, mixed> $metadata
     */
    #[SerializedName('metadata')]
    #[Type('array<string, mixed>|null')]
    #[SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  array<Posting>  $postings
     * @param  \DateTime  $timestamp
     * @param  BigInteger  $txid
     * @param  ?array<string, array<string, Volume>>  $postCommitVolumes
     * @param  ?array<string, array<string, Volume>>  $preCommitVolumes
     * @param  ?string  $reference
     * @param  ?array<string, mixed>  $metadata
     * @phpstan-pure
     */
    public function __construct(array $postings, \DateTime $timestamp, BigInteger $txid, ?array $postCommitVolumes = null, ?array $preCommitVolumes = null, ?string $reference = null, ?array $metadata = null)
    {
        $this->postings = $postings;
        $this->timestamp = $timestamp;
        $this->txid = $txid;
        $this->postCommitVolumes = $postCommitVolumes;
        $this->preCommitVolumes = $preCommitVolumes;
        $this->reference = $reference;
        $this->metadata = $metadata;
    }
}