<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;


class V2AccountResponse
{
    /**
     *
     * @var \formance\stack\Models\Ledger\V2Account $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Ledger\V2Account')]
    public V2Account $data;

    /**
     * @param  \formance\stack\Models\Ledger\V2Account  $data
     * @phpstan-pure
     */
    public function __construct(V2Account $data)
    {
        $this->data = $data;
    }
}