<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Speakeasy\Serializer\Annotation\SerializedName;


class V2BulkElementResultDeleteMetadata
{
    /**
     *
     * @var int $logID
     */
    #[SerializedName('logID')]
    public int $logID;

    /**
     *
     * @var string $responseType
     */
    #[SerializedName('responseType')]
    public string $responseType;

    /**
     * @param  int  $logID
     * @param  string  $responseType
     * @phpstan-pure
     */
    public function __construct(int $logID, string $responseType)
    {
        $this->logID = $logID;
        $this->responseType = $responseType;
    }
}