<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


/** V2ChartSegment - Segment within a chart of accounts */
class V2ChartSegment
{
    /**
     * $dotMetadata
     *
     * @var ?array<string, V2ChartAccountMetadata> $dotMetadata
     */
    #[SerializedName('.metadata')]
    #[Type('array<string, \formance\stack\Models\Ledger\V2ChartAccountMetadata>|null')]
    #[SkipWhenNull]
    public ?array $dotMetadata = null;

    /**
     *
     * @var ?string $dotPattern
     */
    #[SerializedName('.pattern')]
    #[SkipWhenNull]
    public ?string $dotPattern = null;

    /**
     *
     * @var ?V2ChartAccountRules $dotRules
     */
    #[SerializedName('.rules')]
    #[Type('\formance\stack\Models\Ledger\V2ChartAccountRules|null')]
    #[SkipWhenNull]
    public ?V2ChartAccountRules $dotRules = null;

    /**
     *
     * @var ?DotSelf $dotSelf
     */
    #[SerializedName('.self')]
    #[Type('\formance\stack\Models\Ledger\DotSelf|null')]
    #[SkipWhenNull]
    public ?DotSelf $dotSelf = null;

    /**
     * $additionalProperties
     *
     * @var ?array<string, V2ChartSegment> $additionalProperties
     */
    #[SerializedName('additionalProperties')]
    #[Type('array<string, \formance\stack\Models\Ledger\V2ChartSegment>|null')]
    #[SkipWhenNull]
    public ?array $additionalProperties = null;

    /**
     * @param  ?array<string, V2ChartAccountMetadata>  $dotMetadata
     * @param  ?string  $dotPattern
     * @param  ?V2ChartAccountRules  $dotRules
     * @param  ?DotSelf  $dotSelf
     * @param  ?array<string, V2ChartSegment>  $additionalProperties
     * @phpstan-pure
     */
    public function __construct(?array $dotMetadata = null, ?string $dotPattern = null, ?V2ChartAccountRules $dotRules = null, ?DotSelf $dotSelf = null, ?array $additionalProperties = null)
    {
        $this->dotMetadata = $dotMetadata;
        $this->dotPattern = $dotPattern;
        $this->dotRules = $dotRules;
        $this->dotSelf = $dotSelf;
        $this->additionalProperties = $additionalProperties;
    }
}