<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class V2Exporter
{
    /**
     * $config
     *
     * @var array<string, mixed> $config
     */
    #[SerializedName('config')]
    #[Type('array<string, mixed>')]
    public array $config;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $driver
     */
    #[SerializedName('driver')]
    public string $driver;

    /**
     *
     * @var string $id
     */
    #[SerializedName('id')]
    public string $id;

    /**
     * @param  array<string, mixed>  $config
     * @param  \DateTime  $createdAt
     * @param  string  $driver
     * @param  string  $id
     * @phpstan-pure
     */
    public function __construct(array $config, \DateTime $createdAt, string $driver, string $id)
    {
        $this->config = $config;
        $this->createdAt = $createdAt;
        $this->driver = $driver;
        $this->id = $id;
    }
}