<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class V2Ledger
{
    /**
     *
     * @var \DateTime $addedAt
     */
    #[SerializedName('addedAt')]
    public \DateTime $addedAt;

    /**
     *
     * @var string $bucket
     */
    #[SerializedName('bucket')]
    public string $bucket;

    /**
     *
     * @var string $name
     */
    #[SerializedName('name')]
    public string $name;

    /**
     * $features
     *
     * @var ?array<string, string> $features
     */
    #[SerializedName('features')]
    #[Type('array<string, string>|null')]
    #[SkipWhenNull]
    public ?array $features = null;

    /**
     *
     * @var ?int $id
     */
    #[SerializedName('id')]
    #[SkipWhenNull]
    public ?int $id = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[SerializedName('metadata')]
    #[Type('array<string, string>|null')]
    #[SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?\DateTime $deletedAt
     */
    #[SerializedName('deletedAt')]
    #[SkipWhenNull]
    public ?\DateTime $deletedAt = null;

    /**
     * @param  \DateTime  $addedAt
     * @param  string  $bucket
     * @param  string  $name
     * @param  ?array<string, string>  $features
     * @param  ?int  $id
     * @param  ?array<string, string>  $metadata
     * @param  ?\DateTime  $deletedAt
     * @phpstan-pure
     */
    public function __construct(\DateTime $addedAt, string $bucket, string $name, ?array $features = null, ?int $id = null, ?array $metadata = null, ?\DateTime $deletedAt = null)
    {
        $this->addedAt = $addedAt;
        $this->bucket = $bucket;
        $this->name = $name;
        $this->features = $features;
        $this->id = $id;
        $this->metadata = $metadata;
        $this->deletedAt = $deletedAt;
    }
}