<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;


/** V2LogDataRevertedTransaction - Payload for REVERTED_TRANSACTION log entries. Contains both the original reverted transaction and the new reverting transaction. */
class V2LogDataRevertedTransaction
{
    /**
     * Transaction structure as it appears in log payloads
     *
     * @var V2LogTransaction $v2LogTransaction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('revertedTransaction')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Ledger\V2LogTransaction')]
    public V2LogTransaction $v2LogTransaction;

    /**
     * Transaction structure as it appears in log payloads
     *
     * @var V2LogTransaction $v2LogTransaction1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Ledger\V2LogTransaction')]
    public V2LogTransaction $v2LogTransaction1;

    /**
     * @param  V2LogTransaction  $v2LogTransaction
     * @param  V2LogTransaction  $v2LogTransaction1
     * @phpstan-pure
     */
    public function __construct(V2LogTransaction $v2LogTransaction, V2LogTransaction $v2LogTransaction1)
    {
        $this->v2LogTransaction = $v2LogTransaction;
        $this->v2LogTransaction1 = $v2LogTransaction1;
    }
}