<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


/** V2SchemaData - Schema data structure for ledger schemas */
class V2SchemaData
{
    /**
     * Chart of account
     *
     * @var array<string, V2ChartSegment> $chart
     */
    #[SerializedName('chart')]
    #[Type('array<string, \formance\stack\Models\Ledger\V2ChartSegment>')]
    public array $chart;

    /**
     * Query templates
     *
     * @var ?array<string, V2QueryTemplate> $queries
     */
    #[SerializedName('queries')]
    #[Type('array<string, \formance\stack\Models\Ledger\V2QueryTemplate>|null')]
    #[SkipWhenNull]
    public ?array $queries = null;

    /**
     * Transaction templates
     *
     * @var ?array<string, V2TransactionTemplate> $transactions
     */
    #[SerializedName('transactions')]
    #[Type('array<string, \formance\stack\Models\Ledger\V2TransactionTemplate>|null')]
    #[SkipWhenNull]
    public ?array $transactions = null;

    /**
     * @param  array<string, V2ChartSegment>  $chart
     * @param  ?array<string, V2QueryTemplate>  $queries
     * @param  ?array<string, V2TransactionTemplate>  $transactions
     * @phpstan-pure
     */
    public function __construct(array $chart, ?array $queries = null, ?array $transactions = null)
    {
        $this->chart = $chart;
        $this->queries = $queries;
        $this->transactions = $transactions;
    }
}