<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;
use Brick\Math\BigInteger;
use Speakeasy\Serializer\Annotation\SerializedName;


class V2Stats
{
    /**
     *
     * @var int $accounts
     */
    #[SerializedName('accounts')]
    public int $accounts;

    /**
     *
     * @var BigInteger $transactions
     */
    #[SerializedName('transactions')]
    public BigInteger $transactions;

    /**
     * @param  int  $accounts
     * @param  BigInteger  $transactions
     * @phpstan-pure
     */
    public function __construct(int $accounts, BigInteger $transactions)
    {
        $this->accounts = $accounts;
        $this->transactions = $transactions;
    }
}