<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Ledger;


class V2TransactionsCursorResponse
{
    /**
     *
     * @var \formance\stack\Models\Ledger\V2TransactionsCursorResponseCursor $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Ledger\V2TransactionsCursorResponseCursor')]
    public V2TransactionsCursorResponseCursor $cursor;

    /**
     *
     * @var ?\formance\stack\Models\Ledger\V2TransactionsCursorResponseResource $resource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resource')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Ledger\V2TransactionsCursorResponseResource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V2TransactionsCursorResponseResource $resource = null;

    /**
     * @param  \formance\stack\Models\Ledger\V2TransactionsCursorResponseCursor  $cursor
     * @param  ?\formance\stack\Models\Ledger\V2TransactionsCursorResponseResource  $resource
     * @phpstan-pure
     */
    public function __construct(V2TransactionsCursorResponseCursor $cursor, ?V2TransactionsCursorResponseResource $resource = null)
    {
        $this->cursor = $cursor;
        $this->resource = $resource;
    }
}