workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    stacks-source:
        inputs:
            - location: registry.speakeasyapi.dev/formance/formance/stacks-source@LATEST_RELEASE
        registry:
            location: registry.speakeasyapi.dev/formance/formance/stacks-source
targets:
    formance-sdk-php:
        target: php
        source: stacks-source
        publish:
            packagist:
                username: $PACKAGIST_USERNAME
                token: $PACKAGIST_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/stacks-source-php-code-samples
            labelOverride:
                fixedValue: Php (SDK)
            blocking: false
