workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v2.1.0-beta.2/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/my-source
targets:
    formance-sdk-php:
        target: php
        source: my-source
        publish:
            packagist:
                username: $PACKAGIST_USERNAME
                token: $PACKAGIST_TOKEN
