<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Models\Shared;
use formance\stack\Utils\SpeakeasyMetadata;
class CreateWalletRequest
{
    /**
     *
     * @var ?Shared\CreateWalletRequest $createWalletRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?Shared\CreateWalletRequest $createWalletRequest = null;

    /**
     * Use an idempotency key
     *
     * @var ?string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public ?string $idempotencyKey = null;

    /**
     * @param  ?Shared\CreateWalletRequest  $createWalletRequest
     * @param  ?string  $idempotencyKey
     */
    public function __construct(?Shared\CreateWalletRequest $createWalletRequest = null, ?string $idempotencyKey = null)
    {
        $this->createWalletRequest = $createWalletRequest;
        $this->idempotencyKey = $idempotencyKey;
    }
}