<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Utils\SpeakeasyMetadata;
class EvaluateRuleRequest
{
    /**
     * The rule ID.
     *
     * @var string $ruleID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ruleID')]
    public string $ruleID;

    /**
     *
     * @var ?\formance\stack\Models\Reconciliation\EvaluateRuleRequest $evaluateRuleRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\formance\stack\Models\Reconciliation\EvaluateRuleRequest $evaluateRuleRequest = null;

    /**
     * @param  string  $ruleID
     * @param  ?\formance\stack\Models\Reconciliation\EvaluateRuleRequest  $evaluateRuleRequest
     * @phpstan-pure
     */
    public function __construct(string $ruleID, ?\formance\stack\Models\Reconciliation\EvaluateRuleRequest $evaluateRuleRequest = null)
    {
        $this->ruleID = $ruleID;
        $this->evaluateRuleRequest = $evaluateRuleRequest;
    }
}