<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;
use formance\stack\Models\Orchestration\GetWorkflowInstanceHistoryStageResponse;
use Psr\Http\Message\ResponseInterface;


class GetInstanceStageHistoryResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ResponseInterface $rawResponse
     */
    public ResponseInterface $rawResponse;

    /**
     * The workflow instance stage history
     *
     * @var ?GetWorkflowInstanceHistoryStageResponse $getWorkflowInstanceHistoryStageResponse
     */
    public ?GetWorkflowInstanceHistoryStageResponse $getWorkflowInstanceHistoryStageResponse = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  ResponseInterface  $rawResponse
     * @param  ?GetWorkflowInstanceHistoryStageResponse  $getWorkflowInstanceHistoryStageResponse
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, ResponseInterface $rawResponse, ?GetWorkflowInstanceHistoryStageResponse $getWorkflowInstanceHistoryStageResponse = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->getWorkflowInstanceHistoryStageResponse = $getWorkflowInstanceHistoryStageResponse;
    }
}