<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;
use formance\stack\Models\Payments\AccountsCursor;
use Psr\Http\Message\ResponseInterface;


class ListAccountsPaymentsResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ResponseInterface $rawResponse
     */
    public ResponseInterface $rawResponse;

    /**
     * OK
     *
     * @var ?AccountsCursor $accountsCursor
     */
    public ?AccountsCursor $accountsCursor = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  ResponseInterface  $rawResponse
     * @param  ?AccountsCursor  $accountsCursor
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, ResponseInterface $rawResponse, ?AccountsCursor $accountsCursor = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->accountsCursor = $accountsCursor;
    }
}