<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Utils\SpeakeasyMetadata;
class PaymentsgetAccountRequest
{
    /**
     * The account ID.
     *
     * @var string $accountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountId')]
    public string $accountId;

    /**
     * @param  string  $accountId
     * @phpstan-pure
     */
    public function __construct(string $accountId)
    {
        $this->accountId = $accountId;
    }
}