<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Models\Shared;
use formance\stack\Utils\SpeakeasyMetadata;
class ResetConnectorRequest
{
    /**
     * The name of the connector.
     *
     * @var Shared\Connector $connector
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=connector')]
    public Shared\Connector $connector;

    /**
     * @param  Shared\Connector  $connector
     * @phpstan-pure
     */
    public function __construct(Shared\Connector $connector)
    {
        $this->connector = $connector;
    }
}