<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;


class RunWorkflowResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * General error
     *
     * @var ?\formance\stack\Models\Shared\Error $error
     */
    public ?\formance\stack\Models\Shared\Error $error = null;

    /**
     * The workflow instance
     *
     * @var ?\formance\stack\Models\Shared\RunWorkflowResponse $runWorkflowResponse
     */
    public ?\formance\stack\Models\Shared\RunWorkflowResponse $runWorkflowResponse = null;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    public ?\Psr\Http\Message\ResponseInterface $rawResponse;

    public function __construct()
    {
        $this->contentType = '';
        $this->error = null;
        $this->runWorkflowResponse = null;
        $this->statusCode = 0;
        $this->rawResponse = null;
    }
}