<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Models\Shared;
use formance\stack\Utils\SpeakeasyMetadata;
class UpdateMappingRequest
{
    /**
     *
     * @var ?Shared\Mapping $mapping
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?Shared\Mapping $mapping;

    /**
     * Name of the ledger.
     *
     * @var string $ledger
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ledger')]
    public string $ledger;

    /**
     * @param  string  $ledger
     * @param  ?Shared\Mapping  $mapping
     */
    public function __construct(string $ledger, ?Shared\Mapping $mapping = null)
    {
        $this->ledger = $ledger;
        $this->mapping = $mapping;
    }
}