<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Models\Shared;
use formance\stack\Utils\SpeakeasyMetadata;
class V2CreatePipelineRequest
{
    /**
     * Name of the ledger.
     *
     * @var string $ledger
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ledger')]
    public string $ledger;

    /**
     *
     * @var ?Shared\V2CreatePipelineRequest $v2CreatePipelineRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?Shared\V2CreatePipelineRequest $v2CreatePipelineRequest = null;

    /**
     * @param  string  $ledger
     * @param  ?Shared\V2CreatePipelineRequest  $v2CreatePipelineRequest
     * @phpstan-pure
     */
    public function __construct(string $ledger, ?Shared\V2CreatePipelineRequest $v2CreatePipelineRequest = null)
    {
        $this->ledger = $ledger;
        $this->v2CreatePipelineRequest = $v2CreatePipelineRequest;
    }
}