<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Utils\SpeakeasyMetadata;
class V2GetBalancesAggregatedRequest
{
    /**
     * $requestBody
     *
     * @var array<string, mixed> $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public array $requestBody;

    /**
     * Name of the ledger.
     *
     * @var string $ledger
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ledger')]
    public string $ledger;

    /**
     *
     * @var ?\DateTime $pit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pit,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $pit = null;

    /**
     * Use insertion date instead of effective date
     *
     * @var ?bool $useInsertionDate
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=useInsertionDate')]
    public ?bool $useInsertionDate = null;

    /**
     * @param  array<string, mixed>  $requestBody
     * @param  string  $ledger
     * @param  ?\DateTime  $pit
     * @param  ?bool  $useInsertionDate
     * @phpstan-pure
     */
    public function __construct(array $requestBody, string $ledger, ?\DateTime $pit = null, ?bool $useInsertionDate = null)
    {
        $this->requestBody = $requestBody;
        $this->ledger = $ledger;
        $this->pit = $pit;
        $this->useInsertionDate = $useInsertionDate;
    }
}