<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Models\Payments\V3PaymentServiceUserCreateLinkRequest;
use formance\stack\Utils\SpeakeasyMetadata;
class V3CreateLinkForPaymentServiceUserRequest
{
    /**
     * The connector ID
     *
     * @var string $connectorID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=connectorID')]
    public string $connectorID;

    /**
     * The payment service user ID
     *
     * @var string $paymentServiceUserID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=paymentServiceUserID')]
    public string $paymentServiceUserID;

    /**
     *
     * @var ?V3PaymentServiceUserCreateLinkRequest $v3PaymentServiceUserCreateLinkRequest
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?V3PaymentServiceUserCreateLinkRequest $v3PaymentServiceUserCreateLinkRequest = null;

    /**
     * @param  string  $connectorID
     * @param  string  $paymentServiceUserID
     * @param  ?V3PaymentServiceUserCreateLinkRequest  $v3PaymentServiceUserCreateLinkRequest
     * @phpstan-pure
     */
    public function __construct(string $connectorID, string $paymentServiceUserID, ?V3PaymentServiceUserCreateLinkRequest $v3PaymentServiceUserCreateLinkRequest = null)
    {
        $this->connectorID = $connectorID;
        $this->paymentServiceUserID = $paymentServiceUserID;
        $this->v3PaymentServiceUserCreateLinkRequest = $v3PaymentServiceUserCreateLinkRequest;
    }
}