<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Utils\SpeakeasyMetadata;
class V3GetPaymentRequest
{
    /**
     * The payment ID
     *
     * @var string $paymentID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=paymentID')]
    public string $paymentID;

    /**
     * @param  string  $paymentID
     * @phpstan-pure
     */
    public function __construct(string $paymentID)
    {
        $this->paymentID = $paymentID;
    }
}