<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;

use formance\stack\Utils\SpeakeasyMetadata;
class V3RemoveAccountFromPoolRequest
{
    /**
     * The account ID
     *
     * @var string $accountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=accountID')]
    public string $accountID;

    /**
     * The pool ID
     *
     * @var string $poolID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=poolID')]
    public string $poolID;

    /**
     * @param  string  $accountID
     * @param  string  $poolID
     * @phpstan-pure
     */
    public function __construct(string $accountID, string $poolID)
    {
        $this->accountID = $accountID;
        $this->poolID = $poolID;
    }
}