<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


/** AccountResponse - OK */
class AccountResponse
{
    /**
     *
     * @var Account $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Payments\Account')]
    public Account $data;

    /**
     * @param  Account  $data
     * @phpstan-pure
     */
    public function __construct(Account $data)
    {
        $this->data = $data;
    }
}