<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;


class AddAccountToPoolRequest
{
    /**
     *
     * @var string $accountID
     */
    #[SerializedName('accountID')]
    public string $accountID;

    /**
     * @param  string  $accountID
     * @phpstan-pure
     */
    public function __construct(string $accountID)
    {
        $this->accountID = $accountID;
    }
}