<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class BankAccount
{
    /**
     *
     * @var string $country
     */
    #[SerializedName('country')]
    public string $country;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $id
     */
    #[SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[SerializedName('name')]
    public string $name;

    /**
     *
     * @var ?string $accountID
     */
    #[SerializedName('accountID')]
    #[SkipWhenNull]
    public ?string $accountID = null;

    /**
     *
     * @var ?string $accountNumber
     */
    #[SerializedName('accountNumber')]
    #[SkipWhenNull]
    public ?string $accountNumber = null;

    /**
     *
     * @var ?string $connectorID
     */
    #[SerializedName('connectorID')]
    #[SkipWhenNull]
    public ?string $connectorID = null;

    /**
     *
     * @var ?string $iban
     */
    #[SerializedName('iban')]
    #[SkipWhenNull]
    public ?string $iban = null;

    /**
     *
     * @var ?string $provider
     */
    #[SerializedName('provider')]
    #[SkipWhenNull]
    public ?string $provider = null;

    /**
     * $relatedAccounts
     *
     * @var ?array<BankAccountRelatedAccounts> $relatedAccounts
     */
    #[SerializedName('relatedAccounts')]
    #[Type('array<\formance\stack\Models\Payments\BankAccountRelatedAccounts>|null')]
    #[SkipWhenNull]
    public ?array $relatedAccounts = null;

    /**
     *
     * @var ?string $swiftBicCode
     */
    #[SerializedName('swiftBicCode')]
    #[SkipWhenNull]
    public ?string $swiftBicCode = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[SerializedName('metadata')]
    #[Type('array<string, string>|null')]
    #[SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  string  $country
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  string  $name
     * @param  ?string  $accountID
     * @param  ?string  $accountNumber
     * @param  ?string  $connectorID
     * @param  ?string  $iban
     * @param  ?string  $provider
     * @param  ?array<BankAccountRelatedAccounts>  $relatedAccounts
     * @param  ?string  $swiftBicCode
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(string $country, \DateTime $createdAt, string $id, string $name, ?string $accountID = null, ?string $accountNumber = null, ?string $connectorID = null, ?string $iban = null, ?string $provider = null, ?array $relatedAccounts = null, ?string $swiftBicCode = null, ?array $metadata = null)
    {
        $this->country = $country;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->name = $name;
        $this->accountID = $accountID;
        $this->accountNumber = $accountNumber;
        $this->connectorID = $connectorID;
        $this->iban = $iban;
        $this->provider = $provider;
        $this->relatedAccounts = $relatedAccounts;
        $this->swiftBicCode = $swiftBicCode;
        $this->metadata = $metadata;
    }
}