<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


/** BankAccountResponse - OK */
class BankAccountResponse
{
    /**
     *
     * @var BankAccount $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Payments\BankAccount')]
    public BankAccount $data;

    /**
     * @param  BankAccount  $data
     * @phpstan-pure
     */
    public function __construct(BankAccount $data)
    {
        $this->data = $data;
    }
}