<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/** Config - The connector's configuration, whose shape depends on the provider */
class Config
{

    public function __construct()
    {
    }
}