<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


/** ConnectorResponse - OK */
class ConnectorResponse
{
    /**
     *
     * @var Data $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Payments\Data')]
    public Data $data;

    /**
     * @param  Data  $data
     * @phpstan-pure
     */
    public function __construct(Data $data)
    {
        $this->data = $data;
    }
}