<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Brick\Math\BigInteger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class PaymentAdjustment
{
    /**
     *
     * @var BigInteger $amount
     */
    #[SerializedName('amount')]
    public BigInteger $amount;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var PaymentAdjustmentRaw $raw
     */
    #[SerializedName('raw')]
    #[Type('\formance\stack\Models\Payments\PaymentAdjustmentRaw')]
    public PaymentAdjustmentRaw $raw;

    /**
     *
     * @var string $reference
     */
    #[SerializedName('reference')]
    public string $reference;

    /**
     *
     * @var PaymentStatus $status
     */
    #[SerializedName('status')]
    #[Type('\formance\stack\Models\Payments\PaymentStatus')]
    public PaymentStatus $status;

    /**
     * @param  BigInteger  $amount
     * @param  \DateTime  $createdAt
     * @param  PaymentAdjustmentRaw  $raw
     * @param  string  $reference
     * @param  PaymentStatus  $status
     * @phpstan-pure
     */
    public function __construct(BigInteger $amount, \DateTime $createdAt, PaymentAdjustmentRaw $raw, string $reference, PaymentStatus $status)
    {
        $this->amount = $amount;
        $this->createdAt = $createdAt;
        $this->raw = $raw;
        $this->reference = $reference;
        $this->status = $status;
    }
}