<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/** PaymentResponse - OK */
class PaymentResponse
{
    /**
     *
     * @var Payment $payment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\Payment')]
    public Payment $payment;

    /**
     * @param  Payment  $payment
     * @phpstan-pure
     */
    public function __construct(Payment $payment)
    {
        $this->payment = $payment;
    }
}