<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/** PoolResponse - OK */
class PoolResponse
{
    /**
     *
     * @var \formance\stack\Models\Payments\Pool $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\Pool')]
    public Pool $data;

    /**
     * @param  \formance\stack\Models\Payments\Pool  $data
     * @phpstan-pure
     */
    public function __construct(Pool $data)
    {
        $this->data = $data;
    }
}