<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/** PoolBalances - Aggregated balances across a pool's accounts */
class PoolBalances
{
    /**
     * Aggregated balance per asset across the pool's accounts
     *
     * @var array<\formance\stack\Models\Payments\PoolBalance> $balances
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('balances')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\formance\stack\Models\Payments\PoolBalance>')]
    public array $balances;

    /**
     * @param  array<\formance\stack\Models\Payments\PoolBalance>  $balances
     * @phpstan-pure
     */
    public function __construct(array $balances)
    {
        $this->balances = $balances;
    }
}