<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


class TransferRequest
{
    /**
     * Amount to transfer, in the asset's smallest unit
     *
     * @var \Brick\Math\BigInteger $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public \Brick\Math\BigInteger $amount;

    /**
     * Asset the transfer is denominated in
     *
     * @var string $asset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('asset')]
    public string $asset;

    /**
     * Provider-side account receiving the funds
     *
     * @var string $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    public string $destination;

    /**
     * Provider-side account the funds leave. Defaults to the connector's main account
     *
     * @var ?string $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $source = null;

    /**
     * @param  \Brick\Math\BigInteger  $amount
     * @param  string  $asset
     * @param  string  $destination
     * @param  ?string  $source
     * @phpstan-pure
     */
    public function __construct(\Brick\Math\BigInteger $amount, string $asset, string $destination, ?string $source = null)
    {
        $this->amount = $amount;
        $this->asset = $asset;
        $this->destination = $destination;
        $this->source = $source;
    }
}