<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/** TransferResponse - OK */
class TransferResponse
{
    /**
     * Identifier of the transfer created at the provider
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * @param  ?string  $id
     * @phpstan-pure
     */
    public function __construct(?string $id = null)
    {
        $this->id = $id;
    }
}