<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class UpdatePoolQueryRequest
{
    /**
     * $query
     *
     * @var array<string, mixed> $query
     */
    #[SerializedName('query')]
    #[Type('array<string, mixed>')]
    public array $query;

    /**
     * @param  array<string, mixed>  $query
     * @phpstan-pure
     */
    public function __construct(array $query)
    {
        $this->query = $query;
    }
}