<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;


class V3AdyenConfig
{
    /**
     *
     * @var string $apiKey
     */
    #[SerializedName('apiKey')]
    public string $apiKey;

    /**
     *
     * @var string $companyID
     */
    #[SerializedName('companyID')]
    public string $companyID;

    /**
     *
     * @var string $name
     */
    #[SerializedName('name')]
    public string $name;

    /**
     *
     * @var ?string $liveEndpointPrefix
     */
    #[SerializedName('liveEndpointPrefix')]
    #[SkipWhenNull]
    public ?string $liveEndpointPrefix = null;

    /**
     *
     * @var ?string $webhookPassword
     */
    #[SerializedName('webhookPassword')]
    #[SkipWhenNull]
    public ?string $webhookPassword = null;

    /**
     *
     * @var ?string $webhookUsername
     */
    #[SerializedName('webhookUsername')]
    #[SkipWhenNull]
    public ?string $webhookUsername = null;

    /**
     *
     * @var ?int $pageSize
     * @deprecated  field: From v3.1, this parameter will be ignored.
     */
    #[SerializedName('pageSize')]
    #[SkipWhenNull]
    public ?int $pageSize = null;

    /**
     *
     * @var ?string $pollingPeriod
     */
    #[SerializedName('pollingPeriod')]
    #[SkipWhenNull]
    public ?string $pollingPeriod = null;

    /**
     *
     * @var ?string $provider
     */
    #[SerializedName('provider')]
    #[SkipWhenNull]
    public ?string $provider = null;

    /**
     * @param  string  $apiKey
     * @param  string  $companyID
     * @param  string  $name
     * @param  ?string  $liveEndpointPrefix
     * @param  ?int  $pageSize
     * @param  ?string  $pollingPeriod
     * @param  ?string  $provider
     * @param  ?string  $webhookPassword
     * @param  ?string  $webhookUsername
     * @phpstan-pure
     */
    public function __construct(string $apiKey, string $companyID, string $name, ?string $liveEndpointPrefix = null, ?string $webhookPassword = null, ?string $webhookUsername = null, ?int $pageSize = 25, ?string $pollingPeriod = '30m', ?string $provider = 'Adyen')
    {
        $this->apiKey = $apiKey;
        $this->companyID = $companyID;
        $this->name = $name;
        $this->liveEndpointPrefix = $liveEndpointPrefix;
        $this->webhookPassword = $webhookPassword;
        $this->webhookUsername = $webhookUsername;
        $this->pageSize = $pageSize;
        $this->pollingPeriod = $pollingPeriod;
        $this->provider = $provider;
    }
}