<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/**
 * Plugin capability advertised by a connector. Distinct from the Formance gateway "module capabilities" (which are version-gated); these reflect what the underlying PSP integration actually exposes.
 *
 *
 */
enum V3Capability: string
{
    case FetchAccounts = 'FETCH_ACCOUNTS';
    case FetchBalances = 'FETCH_BALANCES';
    case FetchExternalAccounts = 'FETCH_EXTERNAL_ACCOUNTS';
    case FetchPayments = 'FETCH_PAYMENTS';
    case FetchOthers = 'FETCH_OTHERS';
    case FetchOrders = 'FETCH_ORDERS';
    case FetchConversions = 'FETCH_CONVERSIONS';
    case CreateWebhooks = 'CREATE_WEBHOOKS';
    case TranslateWebhooks = 'TRANSLATE_WEBHOOKS';
    case CreateBankAccount = 'CREATE_BANK_ACCOUNT';
    case CreateTransfer = 'CREATE_TRANSFER';
    case CreatePayout = 'CREATE_PAYOUT';
    case AllowFormanceAccountCreation = 'ALLOW_FORMANCE_ACCOUNT_CREATION';
    case AllowFormancePaymentCreation = 'ALLOW_FORMANCE_PAYMENT_CREATION';
}
