<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;


class V3ConnectorConfigsResponseData
{
    /**
     *
     * @var string $dataType
     */
    #[SerializedName('dataType')]
    public string $dataType;

    /**
     *
     * @var bool $required
     */
    #[SerializedName('required')]
    public bool $required;

    /**
     *
     * @var ?string $defaultValue
     */
    #[SerializedName('defaultValue')]
    #[SkipWhenNull]
    public ?string $defaultValue = null;

    /**
     * @param  string  $dataType
     * @param  bool  $required
     * @param  ?string  $defaultValue
     * @phpstan-pure
     */
    public function __construct(string $dataType, bool $required, ?string $defaultValue = null)
    {
        $this->dataType = $dataType;
        $this->required = $required;
        $this->defaultValue = $defaultValue;
    }
}