<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/**
 * Lifecycle of a conversion.
 *
 * `PENDING` — accepted by the PSP, not yet settled.
 * `COMPLETED` — settled, terminal.
 * `FAILED` — rejected or reverted, terminal. See `error`.
 *
 */
enum V3ConversionStatusEnum: string
{
    case Unknown = 'UNKNOWN';
    case Pending = 'PENDING';
    case Completed = 'COMPLETED';
    case Failed = 'FAILED';
}
