<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


class V3CreatePaymentAdjustmentRequest
{
    /**
     *
     * @var V3PaymentStatusEnum $v3PaymentStatusEnum
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3PaymentStatusEnum')]
    public V3PaymentStatusEnum $v3PaymentStatusEnum;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     *
     * @var ?\Brick\Math\BigInteger $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $amount = null;

    /**
     *
     * @var ?string $asset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('asset')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $asset = null;

    /**
     * $v3Metadata
     *
     * @var ?array<string, string> $v3Metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $v3Metadata = null;

    /**
     * @param  V3PaymentStatusEnum  $v3PaymentStatusEnum
     * @param  \DateTime  $createdAt
     * @param  string  $reference
     * @param  ?\Brick\Math\BigInteger  $amount
     * @param  ?string  $asset
     * @param  ?array<string, string>  $v3Metadata
     * @phpstan-pure
     */
    public function __construct(V3PaymentStatusEnum $v3PaymentStatusEnum, \DateTime $createdAt, string $reference, ?\Brick\Math\BigInteger $amount = null, ?string $asset = null, ?array $v3Metadata = null)
    {
        $this->v3PaymentStatusEnum = $v3PaymentStatusEnum;
        $this->createdAt = $createdAt;
        $this->reference = $reference;
        $this->amount = $amount;
        $this->asset = $asset;
        $this->v3Metadata = $v3Metadata;
    }
}