<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


class V3GetBankAccountResponse
{
    /**
     *
     * @var \formance\stack\Models\Payments\V3BankAccount $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3BankAccount')]
    public V3BankAccount $data;

    /**
     * @param  \formance\stack\Models\Payments\V3BankAccount  $data
     * @phpstan-pure
     */
    public function __construct(V3BankAccount $data)
    {
        $this->data = $data;
    }
}