<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class V3GetPaymentServiceUserResponse
{
    /**
     *
     * @var V3PaymentServiceUser $data
     */
    #[SerializedName('data')]
    #[Type('\formance\stack\Models\Payments\V3PaymentServiceUser')]
    public V3PaymentServiceUser $data;

    /**
     * @param  V3PaymentServiceUser  $data
     * @phpstan-pure
     */
    public function __construct(V3PaymentServiceUser $data)
    {
        $this->data = $data;
    }
}