<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;


class V3IncreaseConfig
{
    /**
     *
     * @var string $apiKey
     */
    #[SerializedName('apiKey')]
    public string $apiKey;

    /**
     *
     * @var string $endpoint
     */
    #[SerializedName('endpoint')]
    public string $endpoint;

    /**
     *
     * @var string $name
     */
    #[SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $webhookSharedSecret
     */
    #[SerializedName('webhookSharedSecret')]
    public string $webhookSharedSecret;

    /**
     *
     * @var ?int $pageSize
     * @deprecated  field: From v3.1, this parameter will be ignored.
     */
    #[SerializedName('pageSize')]
    #[SkipWhenNull]
    public ?int $pageSize = null;

    /**
     *
     * @var ?string $pollingPeriod
     */
    #[SerializedName('pollingPeriod')]
    #[SkipWhenNull]
    public ?string $pollingPeriod = null;

    /**
     *
     * @var ?string $provider
     */
    #[SerializedName('provider')]
    #[SkipWhenNull]
    public ?string $provider = null;

    /**
     * @param  string  $apiKey
     * @param  string  $endpoint
     * @param  string  $name
     * @param  string  $webhookSharedSecret
     * @param  ?int  $pageSize
     * @param  ?string  $pollingPeriod
     * @param  ?string  $provider
     * @phpstan-pure
     */
    public function __construct(string $apiKey, string $endpoint, string $name, string $webhookSharedSecret, ?int $pageSize = 25, ?string $pollingPeriod = '30m', ?string $provider = 'Increase')
    {
        $this->apiKey = $apiKey;
        $this->endpoint = $endpoint;
        $this->name = $name;
        $this->webhookSharedSecret = $webhookSharedSecret;
        $this->pageSize = $pageSize;
        $this->pollingPeriod = $pollingPeriod;
        $this->provider = $provider;
    }
}