<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


class V3InitiatePaymentRequest
{
    /**
     * Amount to move, in the asset's smallest unit
     *
     * @var \Brick\Math\BigInteger $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public \Brick\Math\BigInteger $amount;

    /**
     * Asset the payment is denominated in
     *
     * @var string $asset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('asset')]
    public string $asset;

    /**
     * Identifier of the connector to execute the payment through
     *
     * @var string $connectorID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectorID')]
    public string $connectorID;

    /**
     * Human-readable description carried with the payment
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Caller-supplied identifier for the initiation, used to deduplicate retries
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     * When the payment should be executed
     *
     * @var \DateTime $scheduledAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scheduledAt')]
    public \DateTime $scheduledAt;

    /**
     * Kind of movement a payment initiation performs, such as a transfer or a payout
     *
     * @var \formance\stack\Models\Payments\V3PaymentInitiationTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3PaymentInitiationTypeEnum')]
    public V3PaymentInitiationTypeEnum $type;

    /**
     * Identifier of the account the funds reach
     *
     * @var ?string $destinationAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destinationAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationAccountID = null;

    /**
     * Arbitrary key/value pairs attached to the resource
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Identifier of the account the funds leave
     *
     * @var ?string $sourceAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sourceAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceAccountID = null;

    /**
     * @param  \Brick\Math\BigInteger  $amount
     * @param  string  $asset
     * @param  string  $connectorID
     * @param  string  $description
     * @param  string  $reference
     * @param  \DateTime  $scheduledAt
     * @param  \formance\stack\Models\Payments\V3PaymentInitiationTypeEnum  $type
     * @param  ?string  $destinationAccountID
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $sourceAccountID
     * @phpstan-pure
     */
    public function __construct(\Brick\Math\BigInteger $amount, string $asset, string $connectorID, string $description, string $reference, \DateTime $scheduledAt, V3PaymentInitiationTypeEnum $type, ?string $destinationAccountID = null, ?array $metadata = null, ?string $sourceAccountID = null)
    {
        $this->amount = $amount;
        $this->asset = $asset;
        $this->connectorID = $connectorID;
        $this->description = $description;
        $this->reference = $reference;
        $this->scheduledAt = $scheduledAt;
        $this->type = $type;
        $this->destinationAccountID = $destinationAccountID;
        $this->metadata = $metadata;
        $this->sourceAccountID = $sourceAccountID;
    }
}