<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


/**
 * V3Order - A trade order submitted to an exchange-style PSP. Orders are read-only
 *
 * in the Formance API: they are fetched from the underlying connector.
 * Status transitions are captured via the `adjustments` array; each
 * adjustment is a point-in-time snapshot from the PSP.
 *
 */
class V3Order
{
    /**
     * Amount of base asset the order was placed for, as an integer at the base asset's precision.
     *
     * @var \Brick\Math\BigInteger $baseQuantityOrdered
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('baseQuantityOrdered')]
    public \Brick\Math\BigInteger $baseQuantityOrdered;

    /**
     * ID of the Formance connector this order was fetched from.
     *
     * @var string $connectorID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectorID')]
    public string $connectorID;

    /**
     * When the order was created on the PSP.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     * Asset being received, in `SYMBOL/precision` form.
     *
     * For BUY: the base currency. For SELL: the quote currency.
     *
     *
     * @var string $destinationAsset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destinationAsset')]
    public string $destinationAsset;

    /**
     * Whether an order buys or sells the base asset.
     *
     * @var \formance\stack\Models\Payments\V3OrderDirectionEnum $direction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('direction')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3OrderDirectionEnum')]
    public V3OrderDirectionEnum $direction;

    /**
     * Formance-assigned unique order ID (composed from the PSP reference and connector ID).
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Provider name of the connector (e.g. `coinbaseprime`).
     *
     * @var string $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    public string $provider;

    /**
     * PSP-assigned order reference. Unique within the connector; used as the storage dedup key.
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     * Asset being spent, in `SYMBOL/precision` form (e.g. `USD/2`,
     *
     * `BTC/8`). For BUY: the quote currency. For SELL: the base
     * currency.
     *
     *
     * @var string $sourceAsset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sourceAsset')]
    public string $sourceAsset;

    /**
     * Lifecycle of an order on the exchange.
     *
     * `PENDING` — accepted by the exchange, not yet working.
     * `OPEN` — live on the book, no fills yet.
     * `PARTIALLY_FILLED` — live on the book, some base quantity filled.
     * `FILLED` — fully filled, terminal.
     * `CANCELLED` — cancelled by the user or system, terminal.
     * `FAILED` — rejected by the exchange, terminal. See `error` for details.
     * `EXPIRED` — `timeInForce` elapsed before full fill, terminal.
     *
     *
     * @var \formance\stack\Models\Payments\V3OrderStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3OrderStatusEnum')]
    public V3OrderStatusEnum $status;

    /**
     * How long an order is valid on the exchange.
     *
     * `GOOD_UNTIL_CANCELLED` — rests until explicitly cancelled.
     * `GOOD_UNTIL_DATE_TIME` — rests until `expiresAt`.
     * `IMMEDIATE_OR_CANCEL` — fill immediately, cancel any unfilled portion.
     * `FILL_OR_KILL` — fill fully and immediately, or cancel entirely.
     *
     *
     * @var \formance\stack\Models\Payments\V3TimeInForceEnum $timeInForce
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timeInForce')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3TimeInForceEnum')]
    public V3TimeInForceEnum $timeInForce;

    /**
     * Exchange order type. Determines which price fields are meaningful on
     *
     * `V3Order`: LIMIT-family types use `limitPrice`; STOP-family types use
     * `stopPrice`; TWAP/VWAP are time-weighted execution algorithms.
     *
     *
     * @var \formance\stack\Models\Payments\V3OrderTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3OrderTypeEnum')]
    public V3OrderTypeEnum $type;

    /**
     * When Formance last observed a state change on the order. Equivalent to the latest adjustment's `createdAt`.
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public \DateTime $updatedAt;

    /**
     * Ordered history of state snapshots for this order. The most recent element reflects the current `status`.
     *
     * @var ?array<\formance\stack\Models\Payments\V3OrderAdjustment> $adjustments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('adjustments')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\formance\stack\Models\Payments\V3OrderAdjustment>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $adjustments = null;

    /**
     * Volume-weighted average price across all fills so far, in `priceAsset` precision. Analytics field — may be absent if the PSP does not report it.
     *
     * @var ?\Brick\Math\BigInteger $averageFillPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('averageFillPrice')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $averageFillPrice = null;

    /**
     * Amount of base asset filled so far, as an integer at the base asset's precision. Null before any fill.
     *
     * @var ?\Brick\Math\BigInteger $baseQuantityFilled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('baseQuantityFilled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $baseQuantityFilled = null;

    /**
     * Client-assigned ID supplied to the PSP for placement idempotency
     *
     * (e.g. Coinbase `client_order_id`, Kraken `cl_ord_id`, Binance
     * `clientOrderId`). Stored for traceability only — Formance does
     * NOT dedup on this field.
     *
     *
     * @var ?string $clientOrderID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clientOrderID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clientOrderID = null;

    /**
     * Formance account ID of the wallet the destination asset was credited to. Null if unresolvable.
     *
     * @var ?string $destinationAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destinationAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationAccountID = null;

    /**
     * Human-readable error from the PSP (e.g. rejection reason) when `status` is `FAILED`. Null otherwise.
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * Expiration instant for `GOOD_UNTIL_DATE_TIME` orders. Null for other time-in-force values.
     *
     * @var ?\DateTime $expiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiresAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $expiresAt = null;

    /**
     * Commission charged by the PSP for the order, as an integer in `feeAsset` precision.
     *
     * @var ?\Brick\Math\BigInteger $fee
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fee')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $fee = null;

    /**
     * Currency the fee is denominated in, in `SYMBOL/precision` form. Typically the quote asset.
     *
     * @var ?string $feeAsset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeAsset')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $feeAsset = null;

    /**
     * Maximum price (for BUY) or minimum price (for SELL) at which the order may execute, in `priceAsset` precision. Required for LIMIT-family order types; null otherwise.
     *
     * @var ?\Brick\Math\BigInteger $limitPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('limitPrice')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $limitPrice = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Currency + precision under which `limitPrice`, `stopPrice`, and
     *
     * `averageFillPrice` should be interpreted. Separate from
     * `quoteAsset` because some PSPs return price strings with more
     * decimal digits than the quote currency's natural precision.
     *
     *
     * @var ?string $priceAsset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('priceAsset')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $priceAsset = null;

    /**
     * Total amount of quote currency exchanged so far, as reported by
     *
     * the PSP (e.g. Coinbase `filled_value`), at `quoteAsset`
     * precision. For BUY: amount spent. For SELL: amount received.
     *
     *
     * @var ?\Brick\Math\BigInteger $quoteAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quoteAmount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $quoteAmount = null;

    /**
     * Quote currency with precision (e.g. `USD/2`). Null when the order has no quote-side amounts reported yet.
     *
     * @var ?string $quoteAsset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quoteAsset')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $quoteAsset = null;

    /**
     * Formance account ID of the wallet the source asset was debited
     *
     * from. Null if the PSP did not return enough information to
     * resolve it at ingestion time.
     *
     *
     * @var ?string $sourceAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sourceAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceAccountID = null;

    /**
     * Trigger price at which a STOP / STOP_LIMIT order activates, in `priceAsset` precision. Null for non-stop order types.
     *
     * @var ?\Brick\Math\BigInteger $stopPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stopPrice')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $stopPrice = null;

    /**
     * @param  \Brick\Math\BigInteger  $baseQuantityOrdered
     * @param  string  $connectorID
     * @param  \DateTime  $createdAt
     * @param  string  $destinationAsset
     * @param  \formance\stack\Models\Payments\V3OrderDirectionEnum  $direction
     * @param  string  $id
     * @param  string  $provider
     * @param  string  $reference
     * @param  string  $sourceAsset
     * @param  \formance\stack\Models\Payments\V3OrderStatusEnum  $status
     * @param  \formance\stack\Models\Payments\V3TimeInForceEnum  $timeInForce
     * @param  \formance\stack\Models\Payments\V3OrderTypeEnum  $type
     * @param  \DateTime  $updatedAt
     * @param  ?array<\formance\stack\Models\Payments\V3OrderAdjustment>  $adjustments
     * @param  ?\Brick\Math\BigInteger  $averageFillPrice
     * @param  ?\Brick\Math\BigInteger  $baseQuantityFilled
     * @param  ?string  $clientOrderID
     * @param  ?string  $destinationAccountID
     * @param  ?string  $error
     * @param  ?\DateTime  $expiresAt
     * @param  ?\Brick\Math\BigInteger  $fee
     * @param  ?string  $feeAsset
     * @param  ?\Brick\Math\BigInteger  $limitPrice
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $priceAsset
     * @param  ?\Brick\Math\BigInteger  $quoteAmount
     * @param  ?string  $quoteAsset
     * @param  ?string  $sourceAccountID
     * @param  ?\Brick\Math\BigInteger  $stopPrice
     * @phpstan-pure
     */
    public function __construct(\Brick\Math\BigInteger $baseQuantityOrdered, string $connectorID, \DateTime $createdAt, string $destinationAsset, V3OrderDirectionEnum $direction, string $id, string $provider, string $reference, string $sourceAsset, V3OrderStatusEnum $status, V3TimeInForceEnum $timeInForce, V3OrderTypeEnum $type, \DateTime $updatedAt, ?array $adjustments = null, ?\Brick\Math\BigInteger $averageFillPrice = null, ?\Brick\Math\BigInteger $baseQuantityFilled = null, ?string $clientOrderID = null, ?string $destinationAccountID = null, ?string $error = null, ?\DateTime $expiresAt = null, ?\Brick\Math\BigInteger $fee = null, ?string $feeAsset = null, ?\Brick\Math\BigInteger $limitPrice = null, ?array $metadata = null, ?string $priceAsset = null, ?\Brick\Math\BigInteger $quoteAmount = null, ?string $quoteAsset = null, ?string $sourceAccountID = null, ?\Brick\Math\BigInteger $stopPrice = null)
    {
        $this->baseQuantityOrdered = $baseQuantityOrdered;
        $this->connectorID = $connectorID;
        $this->createdAt = $createdAt;
        $this->destinationAsset = $destinationAsset;
        $this->direction = $direction;
        $this->id = $id;
        $this->provider = $provider;
        $this->reference = $reference;
        $this->sourceAsset = $sourceAsset;
        $this->status = $status;
        $this->timeInForce = $timeInForce;
        $this->type = $type;
        $this->updatedAt = $updatedAt;
        $this->adjustments = $adjustments;
        $this->averageFillPrice = $averageFillPrice;
        $this->baseQuantityFilled = $baseQuantityFilled;
        $this->clientOrderID = $clientOrderID;
        $this->destinationAccountID = $destinationAccountID;
        $this->error = $error;
        $this->expiresAt = $expiresAt;
        $this->fee = $fee;
        $this->feeAsset = $feeAsset;
        $this->limitPrice = $limitPrice;
        $this->metadata = $metadata;
        $this->priceAsset = $priceAsset;
        $this->quoteAmount = $quoteAmount;
        $this->quoteAsset = $quoteAsset;
        $this->sourceAccountID = $sourceAccountID;
        $this->stopPrice = $stopPrice;
    }
}