<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\Type;


class V3PaymentServiceUserConnectionsCursorResponse
{
    /**
     *
     * @var V3PaymentServiceUserConnectionsCursorResponseCursor $cursor
     */
    #[SerializedName('cursor')]
    #[Type('\formance\stack\Models\Payments\V3PaymentServiceUserConnectionsCursorResponseCursor')]
    public V3PaymentServiceUserConnectionsCursorResponseCursor $cursor;

    /**
     * @param  V3PaymentServiceUserConnectionsCursorResponseCursor  $cursor
     * @phpstan-pure
     */
    public function __construct(V3PaymentServiceUserConnectionsCursorResponseCursor $cursor)
    {
        $this->cursor = $cursor;
    }
}