<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;
use Brick\Math\BigInteger;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class V3PaymentAdjustment
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $id
     */
    #[SerializedName('id')]
    public string $id;

    /**
     *
     * @var V3PaymentAdjustmentRaw $raw
     */
    #[SerializedName('raw')]
    #[Type('\formance\stack\Models\Payments\V3PaymentAdjustmentRaw')]
    public V3PaymentAdjustmentRaw $raw;

    /**
     *
     * @var string $reference
     */
    #[SerializedName('reference')]
    public string $reference;

    /**
     *
     * @var V3PaymentStatusEnum $status
     */
    #[SerializedName('status')]
    #[Type('\formance\stack\Models\Payments\V3PaymentStatusEnum')]
    public V3PaymentStatusEnum $status;

    /**
     *
     * @var ?BigInteger $amount
     */
    #[SerializedName('amount')]
    #[SkipWhenNull]
    public ?BigInteger $amount = null;

    /**
     *
     * @var ?string $asset
     */
    #[SerializedName('asset')]
    #[SkipWhenNull]
    public ?string $asset = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[SerializedName('metadata')]
    #[Type('array<string, string>|null')]
    #[SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  V3PaymentAdjustmentRaw  $raw
     * @param  string  $reference
     * @param  V3PaymentStatusEnum  $status
     * @param  ?BigInteger  $amount
     * @param  ?string  $asset
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $id, V3PaymentAdjustmentRaw $raw, string $reference, V3PaymentStatusEnum $status, ?BigInteger $amount = null, ?string $asset = null, ?array $metadata = null)
    {
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->raw = $raw;
        $this->reference = $reference;
        $this->status = $status;
        $this->amount = $amount;
        $this->asset = $asset;
        $this->metadata = $metadata;
    }
}