<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


class V3PaymentInitiationAdjustment
{
    /**
     *
     * @var V3PaymentInitiationStatusEnum $v3PaymentInitiationStatusEnum
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Payments\V3PaymentInitiationStatusEnum')]
    public V3PaymentInitiationStatusEnum $v3PaymentInitiationStatusEnum;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ?\Brick\Math\BigInteger $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $amount = null;

    /**
     *
     * @var ?string $asset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('asset')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $asset = null;

    /**
     * $v3Metadata
     *
     * @var ?array<string, string> $v3Metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $v3Metadata = null;

    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * @param  V3PaymentInitiationStatusEnum  $v3PaymentInitiationStatusEnum
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  ?\Brick\Math\BigInteger  $amount
     * @param  ?string  $asset
     * @param  ?array<string, string>  $v3Metadata
     * @param  ?string  $error
     * @phpstan-pure
     */
    public function __construct(V3PaymentInitiationStatusEnum $v3PaymentInitiationStatusEnum, \DateTime $createdAt, string $id, ?\Brick\Math\BigInteger $amount = null, ?string $asset = null, ?array $v3Metadata = null, ?string $error = null)
    {
        $this->v3PaymentInitiationStatusEnum = $v3PaymentInitiationStatusEnum;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->amount = $amount;
        $this->asset = $asset;
        $this->v3Metadata = $v3Metadata;
        $this->error = $error;
    }
}