<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


class V3PaymentAdjustmentRaw
{

    public function __construct()
    {
    }
}