<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Payments;


class V3Schedule
{
    /**
     *
     * @var string $connectorID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectorID')]
    public string $connectorID;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var ?\DateTime $pausedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pausedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $pausedAt = null;

    /**
     *
     * @var ?string $pausedReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pausedReason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $pausedReason = null;

    /**
     * @param  string  $connectorID
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  ?\DateTime  $pausedAt
     * @param  ?string  $pausedReason
     * @phpstan-pure
     */
    public function __construct(string $connectorID, \DateTime $createdAt, string $id, ?\DateTime $pausedAt = null, ?string $pausedReason = null)
    {
        $this->connectorID = $connectorID;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->pausedAt = $pausedAt;
        $this->pausedReason = $pausedReason;
    }
}