<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class AccountWithVolumesAndBalances
{
    /**
     *
     * @var string $address
     */
    #[\JMS\Serializer\Annotation\SerializedName('address')]
    public string $address;

    /**
     * $balances
     *
     * @var ?array<string, int> $balances
     */
    #[\JMS\Serializer\Annotation\SerializedName('balances')]
    #[\JMS\Serializer\Annotation\Type('array<string, int>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $balances = null;

    /**
     * $metadata
     *
     * @var ?array<string, mixed> $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * $volumes
     *
     * @var ?array<string, Volume> $volumes
     */
    #[\JMS\Serializer\Annotation\SerializedName('volumes')]
    #[\JMS\Serializer\Annotation\Type('array<string, \formance\stack\Models\Shared\Volume>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $volumes = null;

    /**
     * @param  string  $address
     * @param  ?array<string, int>  $balances
     * @param  ?array<string, mixed>  $metadata
     * @param  ?string  $type
     * @param  ?array<string, Volume>  $volumes
     */
    public function __construct(string $address, ?array $balances = null, ?array $metadata = null, ?string $type = null, ?array $volumes = null)
    {
        $this->address = $address;
        $this->balances = $balances;
        $this->metadata = $metadata;
        $this->type = $type;
        $this->volumes = $volumes;
    }
}