<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class AccountBalance
{
    /**
     *
     * @var string $accountId
     */
    #[\JMS\Serializer\Annotation\SerializedName('accountId')]
    public string $accountId;

    /**
     *
     * @var string $asset
     */
    #[\JMS\Serializer\Annotation\SerializedName('asset')]
    public string $asset;

    /**
     *
     * @var int $balance
     */
    #[\JMS\Serializer\Annotation\SerializedName('balance')]
    public int $balance;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $currency
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\JMS\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var \DateTime $lastUpdatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('lastUpdatedAt')]
    public \DateTime $lastUpdatedAt;

    /**
     * @param  ?string  $accountId
     * @param  ?string  $asset
     * @param  ?int  $balance
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $currency
     * @param  ?\DateTime  $lastUpdatedAt
     */
    public function __construct(?string $accountId = null, ?string $asset = null, ?int $balance = null, ?\DateTime $createdAt = null, ?string $currency = null, ?\DateTime $lastUpdatedAt = null)
    {
        $this->accountId = $accountId;
        $this->asset = $asset;
        $this->balance = $balance;
        $this->createdAt = $createdAt;
        $this->currency = $currency;
        $this->lastUpdatedAt = $lastUpdatedAt;
    }
}