<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class ActivityCreateTransaction
{
    /**
     *
     * @var ?OrchestrationPostTransaction $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\OrchestrationPostTransaction|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrchestrationPostTransaction $data = null;

    /**
     *
     * @var ?string $ledger
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ledger')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ledger = null;

    /**
     * @param  ?OrchestrationPostTransaction  $data
     * @param  ?string  $ledger
     * @phpstan-pure
     */
    public function __construct(?OrchestrationPostTransaction $data = null, ?string $ledger = null)
    {
        $this->data = $data;
        $this->ledger = $ledger;
    }
}