<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class ConfigInfo
{
    /**
     *
     * @var Config $config
     */
    #[\JMS\Serializer\Annotation\SerializedName('config')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\Config')]
    public Config $config;

    /**
     *
     * @var string $server
     */
    #[\JMS\Serializer\Annotation\SerializedName('server')]
    public string $server;

    /**
     *
     * @var string $version
     */
    #[\JMS\Serializer\Annotation\SerializedName('version')]
    public string $version;

    /**
     * @param  Config  $config
     * @param  string  $server
     * @param  string  $version
     */
    public function __construct(Config $config, string $server, string $version)
    {
        $this->config = $config;
        $this->server = $server;
        $this->version = $version;
    }
}