<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class DebitWalletResponse
{
    /**
     *
     * @var Hold $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\Hold')]
    public Hold $data;

    /**
     * @param  Hold  $data
     * @phpstan-pure
     */
    public function __construct(Hold $data)
    {
        $this->data = $data;
    }
}