<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class DummyPayConfig
{
    /**
     *
     * @var string $directory
     */
    #[\JMS\Serializer\Annotation\SerializedName('directory')]
    public string $directory;

    /**
     * The frequency at which the connector will try to fetch new payment objects from the directory
     *
     * @var ?string $filePollingPeriod
     */
    #[\JMS\Serializer\Annotation\SerializedName('filePollingPeriod')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $filePollingPeriod = null;

    /**
     *
     * @var string $name
     */
    #[\JMS\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var ?int $numberOfAccountsPreGenerated
     */
    #[\JMS\Serializer\Annotation\SerializedName('numberOfAccountsPreGenerated')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $numberOfAccountsPreGenerated = null;

    /**
     *
     * @var ?int $numberOfPaymentsPreGenerated
     */
    #[\JMS\Serializer\Annotation\SerializedName('numberOfPaymentsPreGenerated')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $numberOfPaymentsPreGenerated = null;

    /**
     *
     * @var ?string $prefixFileToIngest
     */
    #[\JMS\Serializer\Annotation\SerializedName('prefixFileToIngest')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $prefixFileToIngest = null;

    /**
     * @param  string  $directory
     * @param  string  $name
     * @param  ?string  $filePollingPeriod
     * @param  ?int  $numberOfAccountsPreGenerated
     * @param  ?int  $numberOfPaymentsPreGenerated
     * @param  ?string  $prefixFileToIngest
     */
    public function __construct(string $directory, string $name, ?string $filePollingPeriod = null, ?int $numberOfAccountsPreGenerated = null, ?int $numberOfPaymentsPreGenerated = null, ?string $prefixFileToIngest = null)
    {
        $this->directory = $directory;
        $this->name = $name;
        $this->filePollingPeriod = $filePollingPeriod;
        $this->numberOfAccountsPreGenerated = $numberOfAccountsPreGenerated;
        $this->numberOfPaymentsPreGenerated = $numberOfPaymentsPreGenerated;
        $this->prefixFileToIngest = $prefixFileToIngest;
    }
}