<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class GetWorkflowInstanceHistoryStageResponse
{
    /**
     * $data
     *
     * @var array<WorkflowInstanceHistoryStage> $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<\formance\stack\Models\Shared\WorkflowInstanceHistoryStage>')]
    public array $data;

    /**
     * @param  array<WorkflowInstanceHistoryStage>  $data
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }
}