<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class ListWalletsResponse
{
    /**
     *
     * @var ListWalletsResponseCursor $cursor
     */
    #[\JMS\Serializer\Annotation\SerializedName('cursor')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\ListWalletsResponseCursor')]
    public ListWalletsResponseCursor $cursor;

    /**
     * @param  ?ListWalletsResponseCursor  $cursor
     */
    public function __construct(?ListWalletsResponseCursor $cursor = null)
    {
        $this->cursor = $cursor;
    }
}