<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class ListTriggersResponse
{
    /**
     * $data
     *
     * @var array<Trigger> $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<\formance\stack\Models\Shared\Trigger>')]
    public array $data;

    /**
     * @param  ?array<Trigger>  $data
     */
    public function __construct(?array $data = null)
    {
        $this->data = $data;
    }
}