<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class OrchestrationPaymentAdjustment
{
    /**
     *
     * @var bool $absolute
     */
    #[\JMS\Serializer\Annotation\SerializedName('absolute')]
    public bool $absolute;

    /**
     *
     * @var int $amount
     */
    #[\JMS\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     *
     * @var \DateTime $date
     */
    #[\JMS\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     *
     * @var OrchestrationPaymentAdjustmentRaw $raw
     */
    #[\JMS\Serializer\Annotation\SerializedName('raw')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\OrchestrationPaymentAdjustmentRaw')]
    public OrchestrationPaymentAdjustmentRaw $raw;

    /**
     *
     * @var OrchestrationPaymentStatus $status
     */
    #[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\OrchestrationPaymentStatus')]
    public OrchestrationPaymentStatus $status;

    /**
     * @param  bool  $absolute
     * @param  int  $amount
     * @param  \DateTime  $date
     * @param  OrchestrationPaymentAdjustmentRaw  $raw
     * @param  OrchestrationPaymentStatus  $status
     */
    public function __construct(bool $absolute, int $amount, \DateTime $date, OrchestrationPaymentAdjustmentRaw $raw, OrchestrationPaymentStatus $status)
    {
        $this->absolute = $absolute;
        $this->amount = $amount;
        $this->date = $date;
        $this->raw = $raw;
        $this->status = $status;
    }
}