<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class PaymentAdjustment
{
    /**
     *
     * @var \Brick\Math\BigInteger $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public \Brick\Math\BigInteger $amount;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var PaymentAdjustmentRaw $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\PaymentAdjustmentRaw')]
    public PaymentAdjustmentRaw $raw;

    /**
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     *
     * @var PaymentStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\PaymentStatus')]
    public PaymentStatus $status;

    /**
     * @param  \Brick\Math\BigInteger  $amount
     * @param  \DateTime  $createdAt
     * @param  PaymentAdjustmentRaw  $raw
     * @param  string  $reference
     * @param  PaymentStatus  $status
     */
    public function __construct(\Brick\Math\BigInteger $amount, \DateTime $createdAt, PaymentAdjustmentRaw $raw, string $reference, PaymentStatus $status)
    {
        $this->amount = $amount;
        $this->createdAt = $createdAt;
        $this->raw = $raw;
        $this->reference = $reference;
        $this->status = $status;
    }
}