<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class Pool
{
    /**
     * $accounts
     *
     * @var array<string> $accounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accounts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $accounts;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * $query
     *
     * @var ?array<string, mixed> $query
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('query')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $query = null;

    /**
     *
     * @var ?PoolTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\PoolTypeEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PoolTypeEnum $type = null;

    /**
     * @param  array<string>  $accounts
     * @param  string  $id
     * @param  string  $name
     * @param  ?array<string, mixed>  $query
     * @param  ?PoolTypeEnum  $type
     * @phpstan-pure
     */
    public function __construct(array $accounts, string $id, string $name, ?array $query = null, ?PoolTypeEnum $type = null)
    {
        $this->accounts = $accounts;
        $this->id = $id;
        $this->name = $name;
        $this->query = $query;
        $this->type = $type;
    }
}