<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class QueryTemplateAccountParams
{
    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     *
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     *
     *
     * @var ?string $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cursor = null;

    /**
     *
     * @var ?string $expand
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expand')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $expand = null;

    /**
     * The maximum number of results to return per page.
     *
     *
     *
     * @var ?int $pageSize
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pageSize')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $pageSize = null;

    /**
     *
     * @var ?\DateTime $pit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pit')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $pit = null;

    /**
     *
     * @var ?V2QueryParamsResource $resource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resource')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2QueryParamsResource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V2QueryParamsResource $resource = null;

    /**
     * Sort results using a field name and order (ascending or descending).
     *
     * Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
     *
     *
     * @var ?string $sort
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sort')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sort = null;

    /**
     * @param  ?string  $cursor
     * @param  ?string  $expand
     * @param  ?int  $pageSize
     * @param  ?\DateTime  $pit
     * @param  ?V2QueryParamsResource  $resource
     * @param  ?string  $sort
     * @phpstan-pure
     */
    public function __construct(?string $cursor = null, ?string $expand = null, ?int $pageSize = null, ?\DateTime $pit = null, ?V2QueryParamsResource $resource = null, ?string $sort = null)
    {
        $this->cursor = $cursor;
        $this->expand = $expand;
        $this->pageSize = $pageSize;
        $this->pit = $pit;
        $this->resource = $resource;
        $this->sort = $sort;
    }
}