<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class ReadTriggerResponse
{
    /**
     *
     * @var Trigger $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\Trigger')]
    public Trigger $data;

    /**
     * @param  ?Trigger  $data
     */
    public function __construct(?Trigger $data = null)
    {
        $this->data = $data;
    }
}