<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class ReconciliationResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('reconciliation')]
    #[\JMS\Serializer\Annotation\Type('formance\stack\Models\Shared\Reconciliation')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Reconciliation $reconciliation = null;
    
	public function __construct()
	{
		$this->reconciliation = null;
	}
}
