<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


/** ReconciliationResponse - OK */
class ReconciliationResponse
{
    /**
     *
     * @var Reconciliation $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\Reconciliation')]
    public Reconciliation $data;

    /**
     * @param  Reconciliation  $data
     */
    public function __construct(Reconciliation $data)
    {
        $this->data = $data;
    }
}