<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class StageDelay
{
    /**
     *
     * @var ?string $duration
     */
    #[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $duration = null;

    /**
     *
     * @var ?\DateTime $until
     */
    #[\JMS\Serializer\Annotation\SerializedName('until')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $until = null;

    /**
     * @param  ?string  $duration
     * @param  ?\DateTime  $until
     */
    public function __construct(?string $duration = null, ?\DateTime $until = null)
    {
        $this->duration = $duration;
        $this->until = $until;
    }
}