<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


enum State: string
{
    case ToDo = 'TO DO';
    case Done = 'DONE';
}
