<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class TaskCurrencyCloud
{
    /**
     *
     * @var string $connectorID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectorID')]
    public string $connectorID;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var TaskCurrencyCloudDescriptor $descriptor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('descriptor')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\TaskCurrencyCloudDescriptor')]
    public TaskCurrencyCloudDescriptor $descriptor;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var TaskStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\TaskStatus')]
    public TaskStatus $status;

    /**
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public \DateTime $updatedAt;

    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     *
     * @var ?TaskCurrencyCloudState $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\TaskCurrencyCloudState|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaskCurrencyCloudState $state = null;

    /**
     * @param  string  $connectorID
     * @param  \DateTime  $createdAt
     * @param  TaskCurrencyCloudDescriptor  $descriptor
     * @param  string  $id
     * @param  TaskStatus  $status
     * @param  \DateTime  $updatedAt
     * @param  ?string  $error
     * @param  ?TaskCurrencyCloudState  $state
     * @phpstan-pure
     */
    public function __construct(string $connectorID, \DateTime $createdAt, TaskCurrencyCloudDescriptor $descriptor, string $id, TaskStatus $status, \DateTime $updatedAt, ?string $error = null, ?TaskCurrencyCloudState $state = null)
    {
        $this->connectorID = $connectorID;
        $this->createdAt = $createdAt;
        $this->descriptor = $descriptor;
        $this->id = $id;
        $this->status = $status;
        $this->updatedAt = $updatedAt;
        $this->error = $error;
        $this->state = $state;
    }
}