<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class TransferInitiationAdjusments
{
    /**
     *
     * @var string $adjustmentID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('adjustmentID')]
    public string $adjustmentID;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var TransferInitiationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\TransferInitiationStatus')]
    public TransferInitiationStatus $status;

    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  string  $adjustmentID
     * @param  \DateTime  $createdAt
     * @param  TransferInitiationStatus  $status
     * @param  ?string  $error
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(string $adjustmentID, \DateTime $createdAt, TransferInitiationStatus $status, ?string $error = null, ?array $metadata = null)
    {
        $this->adjustmentID = $adjustmentID;
        $this->createdAt = $createdAt;
        $this->status = $status;
        $this->error = $error;
        $this->metadata = $metadata;
    }
}