<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2ActivityDebitWallet
{
    /**
     *
     * @var ?V2DebitWalletRequest $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2DebitWalletRequest|null')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?V2DebitWalletRequest $data = null;

    /**
     *
     * @var ?string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;

    /**
     * @param  ?V2DebitWalletRequest  $data
     * @param  ?string  $id
     */
    public function __construct(?V2DebitWalletRequest $data = null, ?string $id = null)
    {
        $this->data = $data;
        $this->id = $id;
    }
}