<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2ActivityCreateTransaction
{
    /**
     *
     * @var ?V2PostTransaction $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2PostTransaction')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?V2PostTransaction $data = null;

    /**
     *
     * @var ?string $ledger
     */
    #[\JMS\Serializer\Annotation\SerializedName('ledger')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ledger = null;

    /**
     * @param  ?V2PostTransaction  $data
     * @param  ?string  $ledger
     */
    public function __construct(?V2PostTransaction $data = null, ?string $ledger = null)
    {
        $this->data = $data;
        $this->ledger = $ledger;
    }
}