<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2BulkElementAddMetadata
{
    /**
     *
     * @var string $action
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action')]
    public string $action;

    /**
     *
     * @var ?V2BulkElementAddMetadataData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2BulkElementAddMetadataData|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V2BulkElementAddMetadataData $data = null;

    /**
     *
     * @var ?string $ik
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ik')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ik = null;

    /**
     * @param  string  $action
     * @param  ?V2BulkElementAddMetadataData  $data
     * @param  ?string  $ik
     * @phpstan-pure
     */
    public function __construct(string $action, ?V2BulkElementAddMetadataData $data = null, ?string $ik = null)
    {
        $this->action = $action;
        $this->data = $data;
        $this->ik = $ik;
    }
}