<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2BulkElementRevertTransactionData
{
    /**
     *
     * @var \Brick\Math\BigInteger $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public \Brick\Math\BigInteger $id;

    /**
     *
     * @var ?bool $atEffectiveDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('atEffectiveDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $atEffectiveDate = null;

    /**
     *
     * @var ?bool $force
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('force')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $force = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  \Brick\Math\BigInteger  $id
     * @param  ?bool  $atEffectiveDate
     * @param  ?bool  $force
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(\Brick\Math\BigInteger $id, ?bool $atEffectiveDate = null, ?bool $force = null, ?array $metadata = null)
    {
        $this->id = $id;
        $this->atEffectiveDate = $atEffectiveDate;
        $this->force = $force;
        $this->metadata = $metadata;
    }
}