<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


enum V2ErrorsEnum: string
{
    case Internal = 'INTERNAL';
    case InsufficientFund = 'INSUFFICIENT_FUND';
    case Validation = 'VALIDATION';
    case Conflict = 'CONFLICT';
    case CompilationFailed = 'COMPILATION_FAILED';
    case MetadataOverride = 'METADATA_OVERRIDE';
    case NotFound = 'NOT_FOUND';
    case RevertOccurring = 'REVERT_OCCURRING';
    case AlreadyRevert = 'ALREADY_REVERT';
    case NoPostings = 'NO_POSTINGS';
    case LedgerNotFound = 'LEDGER_NOT_FOUND';
}
