<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2Hold
{
    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     *
     * @var V2LedgerAccountSubject|V2WalletSubject|null $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2LedgerAccountSubject|\formance\stack\Models\Shared\V2WalletSubject')]
    #[\Speakeasy\Serializer\Annotation\UnionDiscriminator(field: 'type', map: ['V2LedgerAccountSubject' => '\formance\stack\Models\Shared\V2LedgerAccountSubject', 'V2WalletSubject' => '\formance\stack\Models\Shared\V2WalletSubject'])]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public V2LedgerAccountSubject|V2WalletSubject|null $destination = null;

    /**
     * The unique ID of the hold.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Metadata associated with the hold.
     *
     * @var array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>')]
    public array $metadata;

    /**
     * The ID of the wallet the hold is associated with.
     *
     * @var string $walletID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('walletID')]
    public string $walletID;

    /**
     * @param  string  $description
     * @param  string  $id
     * @param  array<string, string>  $metadata
     * @param  string  $walletID
     * @param  V2LedgerAccountSubject|V2WalletSubject|null  $destination
     */
    public function __construct(string $description, string $id, array $metadata, string $walletID, V2LedgerAccountSubject|V2WalletSubject|null $destination = null)
    {
        $this->description = $description;
        $this->id = $id;
        $this->metadata = $metadata;
        $this->walletID = $walletID;
        $this->destination = $destination;
    }
}