<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2LedgerInfoResponse
{
    /**
     *
     * @var ?V2LedgerInfo $data
     */
    #[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2LedgerInfo|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?V2LedgerInfo $data = null;

    /**
     * @param  ?V2LedgerInfo  $data
     */
    public function __construct(?V2LedgerInfo $data = null)
    {
        $this->data = $data;
    }
}