<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2StageSend
{
    /**
     *
     * @var ?V2Monetary $amount
     */
    #[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2Monetary')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?V2Monetary $amount = null;

    /**
     *
     * @var ?V2StageSendDestination $destination
     */
    #[\JMS\Serializer\Annotation\SerializedName('destination')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2StageSendDestination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?V2StageSendDestination $destination = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('array<string, string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $metadata = null;

    /**
     *
     * @var ?V2StageSendSource $source
     */
    #[\JMS\Serializer\Annotation\SerializedName('source')]
    #[\JMS\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2StageSendSource')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?V2StageSendSource $source = null;

    /**
     *
     * @var ?\DateTime $timestamp
     */
    #[\JMS\Serializer\Annotation\SerializedName('timestamp')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $timestamp = null;

    /**
     * @param  ?V2Monetary  $amount
     * @param  ?V2StageSendDestination  $destination
     * @param  ?array<string, string>  $metadata
     * @param  ?V2StageSendSource  $source
     * @param  ?\DateTime  $timestamp
     */
    public function __construct(?V2Monetary $amount = null, ?V2StageSendDestination $destination = null, ?array $metadata = null, ?V2StageSendSource $source = null, ?\DateTime $timestamp = null)
    {
        $this->amount = $amount;
        $this->destination = $destination;
        $this->metadata = $metadata;
        $this->source = $source;
        $this->timestamp = $timestamp;
    }
}