<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2StageSendSource
{
    /**
     *
     * @var ?V2StageSendSourceAccount $account
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2StageSendSourceAccount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V2StageSendSourceAccount $account = null;

    /**
     *
     * @var ?V2StageSendSourcePayment $payment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2StageSendSourcePayment|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V2StageSendSourcePayment $payment = null;

    /**
     *
     * @var ?V2StageSendSourceWallet $wallet
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wallet')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V2StageSendSourceWallet|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?V2StageSendSourceWallet $wallet = null;

    /**
     * @param  ?V2StageSendSourceAccount  $account
     * @param  ?V2StageSendSourcePayment  $payment
     * @param  ?V2StageSendSourceWallet  $wallet
     * @phpstan-pure
     */
    public function __construct(?V2StageSendSourceAccount $account = null, ?V2StageSendSourcePayment $payment = null, ?V2StageSendSourceWallet $wallet = null)
    {
        $this->account = $account;
        $this->payment = $payment;
        $this->wallet = $wallet;
    }
}