<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V2StageStatus
{
    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     *
     * @var string $instanceID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instanceID')]
    public string $instanceID;

    /**
     *
     * @var float $stage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stage')]
    public float $stage;

    /**
     *
     * @var \DateTime $startedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startedAt')]
    public \DateTime $startedAt;

    /**
     *
     * @var ?\DateTime $terminatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('terminatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $terminatedAt = null;

    /**
     * @param  string  $instanceID
     * @param  float  $stage
     * @param  \DateTime  $startedAt
     * @param  ?string  $error
     * @param  ?\DateTime  $terminatedAt
     */
    public function __construct(string $instanceID, float $stage, \DateTime $startedAt, ?string $error = null, ?\DateTime $terminatedAt = null)
    {
        $this->instanceID = $instanceID;
        $this->stage = $stage;
        $this->startedAt = $startedAt;
        $this->error = $error;
        $this->terminatedAt = $terminatedAt;
    }
}