<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V3Account
{
    /**
     *
     * @var string $connectorID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectorID')]
    public string $connectorID;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    public string $provider;

    /**
     *
     * @var V3AccountRaw $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V3AccountRaw')]
    public V3AccountRaw $raw;

    /**
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     *
     * @var V3AccountTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V3AccountTypeEnum')]
    public V3AccountTypeEnum $type;

    /**
     *
     * @var ?string $defaultAsset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('defaultAsset')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $defaultAsset = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  string  $connectorID
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  string  $provider
     * @param  V3AccountRaw  $raw
     * @param  string  $reference
     * @param  V3AccountTypeEnum  $type
     * @param  ?string  $defaultAsset
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(string $connectorID, \DateTime $createdAt, string $id, string $provider, V3AccountRaw $raw, string $reference, V3AccountTypeEnum $type, ?string $defaultAsset = null, ?array $metadata = null, ?string $name = null)
    {
        $this->connectorID = $connectorID;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->provider = $provider;
        $this->raw = $raw;
        $this->reference = $reference;
        $this->type = $type;
        $this->defaultAsset = $defaultAsset;
        $this->metadata = $metadata;
        $this->name = $name;
    }
}