<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V3GetPoolResponse
{
    /**
     *
     * @var V3Pool $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V3Pool')]
    public V3Pool $data;

    /**
     * @param  V3Pool  $data
     * @phpstan-pure
     */
    public function __construct(V3Pool $data)
    {
        $this->data = $data;
    }
}