<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V3PaymentInitiationAdjustment
{
    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var V3PaymentInitiationStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V3PaymentInitiationStatusEnum')]
    public V3PaymentInitiationStatusEnum $status;

    /**
     *
     * @var ?\Brick\Math\BigInteger $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\Brick\Math\BigInteger $amount = null;

    /**
     *
     * @var ?string $asset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('asset')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $asset = null;

    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  V3PaymentInitiationStatusEnum  $status
     * @param  ?\Brick\Math\BigInteger  $amount
     * @param  ?string  $asset
     * @param  ?string  $error
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $id, V3PaymentInitiationStatusEnum $status, ?\Brick\Math\BigInteger $amount = null, ?string $asset = null, ?string $error = null, ?array $metadata = null)
    {
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->status = $status;
        $this->amount = $amount;
        $this->asset = $asset;
        $this->error = $error;
        $this->metadata = $metadata;
    }
}