<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V3PaymentInitiation
{
    /**
     *
     * @var \Brick\Math\BigInteger $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public \Brick\Math\BigInteger $amount;

    /**
     *
     * @var string $asset
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('asset')]
    public string $asset;

    /**
     *
     * @var string $connectorID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connectorID')]
    public string $connectorID;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    public string $provider;

    /**
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     *
     * @var \DateTime $scheduledAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scheduledAt')]
    public \DateTime $scheduledAt;

    /**
     *
     * @var V3PaymentInitiationStatusEnum $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V3PaymentInitiationStatusEnum')]
    public V3PaymentInitiationStatusEnum $status;

    /**
     *
     * @var V3PaymentInitiationTypeEnum $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V3PaymentInitiationTypeEnum')]
    public V3PaymentInitiationTypeEnum $type;

    /**
     *
     * @var ?string $destinationAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destinationAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationAccountID = null;

    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     *
     * @var ?string $sourceAccountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sourceAccountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceAccountID = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  \Brick\Math\BigInteger  $amount
     * @param  string  $asset
     * @param  string  $connectorID
     * @param  \DateTime  $createdAt
     * @param  string  $description
     * @param  string  $id
     * @param  string  $provider
     * @param  string  $reference
     * @param  \DateTime  $scheduledAt
     * @param  V3PaymentInitiationStatusEnum  $status
     * @param  V3PaymentInitiationTypeEnum  $type
     * @param  ?string  $destinationAccountID
     * @param  ?string  $error
     * @param  ?string  $sourceAccountID
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(\Brick\Math\BigInteger $amount, string $asset, string $connectorID, \DateTime $createdAt, string $description, string $id, string $provider, string $reference, \DateTime $scheduledAt, V3PaymentInitiationStatusEnum $status, V3PaymentInitiationTypeEnum $type, ?string $destinationAccountID = null, ?string $error = null, ?string $sourceAccountID = null, ?array $metadata = null)
    {
        $this->amount = $amount;
        $this->asset = $asset;
        $this->connectorID = $connectorID;
        $this->createdAt = $createdAt;
        $this->description = $description;
        $this->id = $id;
        $this->provider = $provider;
        $this->reference = $reference;
        $this->scheduledAt = $scheduledAt;
        $this->status = $status;
        $this->type = $type;
        $this->destinationAccountID = $destinationAccountID;
        $this->error = $error;
        $this->sourceAccountID = $sourceAccountID;
        $this->metadata = $metadata;
    }
}