<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


enum V3PaymentInitiationStatusEnum: string
{
    case Unknown = 'UNKNOWN';
    case WaitingForValidation = 'WAITING_FOR_VALIDATION';
    case Processing = 'PROCESSING';
    case Processed = 'PROCESSED';
    case Failed = 'FAILED';
    case Rejected = 'REJECTED';
    case ReverseProcessing = 'REVERSE_PROCESSING';
    case ReverseFailed = 'REVERSE_FAILED';
    case Reversed = 'REVERSED';
}
