<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class V3PaymentInitiationsCursorResponse
{
    /**
     *
     * @var V3PaymentInitiationsCursorResponseCursor $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\V3PaymentInitiationsCursorResponseCursor')]
    public V3PaymentInitiationsCursorResponseCursor $cursor;

    /**
     * @param  V3PaymentInitiationsCursorResponseCursor  $cursor
     * @phpstan-pure
     */
    public function __construct(V3PaymentInitiationsCursorResponseCursor $cursor)
    {
        $this->cursor = $cursor;
    }
}