<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class WorkflowInstanceHistoryStageOutput
{
    /**
     *
     * @var ?RevertTransactionResponse $createTransaction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('CreateTransaction')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\RevertTransactionResponse|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RevertTransactionResponse $createTransaction = null;

    /**
     *
     * @var ?ActivityDebitWalletOutput $debitWallet
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('DebitWallet')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\ActivityDebitWalletOutput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ActivityDebitWalletOutput $debitWallet = null;

    /**
     *
     * @var ?ActivityGetAccountOutput $getAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('GetAccount')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\ActivityGetAccountOutput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ActivityGetAccountOutput $getAccount = null;

    /**
     *
     * @var ?ActivityGetPaymentOutput $getPayment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('GetPayment')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\ActivityGetPaymentOutput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ActivityGetPaymentOutput $getPayment = null;

    /**
     *
     * @var ?ActivityGetWalletOutput $getWallet
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('GetWallet')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\ActivityGetWalletOutput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ActivityGetWalletOutput $getWallet = null;

    /**
     *
     * @var ?OrchestrationListWalletsResponse $listWallets
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ListWallets')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\OrchestrationListWalletsResponse|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrchestrationListWalletsResponse $listWallets = null;

    /**
     *
     * @var ?RevertTransactionResponse $revertTransaction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('RevertTransaction')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Shared\RevertTransactionResponse|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?RevertTransactionResponse $revertTransaction = null;

    /**
     * @param  ?RevertTransactionResponse  $createTransaction
     * @param  ?ActivityDebitWalletOutput  $debitWallet
     * @param  ?ActivityGetAccountOutput  $getAccount
     * @param  ?ActivityGetPaymentOutput  $getPayment
     * @param  ?ActivityGetWalletOutput  $getWallet
     * @param  ?OrchestrationListWalletsResponse  $listWallets
     * @param  ?RevertTransactionResponse  $revertTransaction
     * @phpstan-pure
     */
    public function __construct(?RevertTransactionResponse $createTransaction = null, ?ActivityDebitWalletOutput $debitWallet = null, ?ActivityGetAccountOutput $getAccount = null, ?ActivityGetPaymentOutput $getPayment = null, ?ActivityGetWalletOutput $getWallet = null, ?OrchestrationListWalletsResponse $listWallets = null, ?RevertTransactionResponse $revertTransaction = null)
    {
        $this->createTransaction = $createTransaction;
        $this->debitWallet = $debitWallet;
        $this->getAccount = $getAccount;
        $this->getPayment = $getPayment;
        $this->getWallet = $getWallet;
        $this->listWallets = $listWallets;
        $this->revertTransaction = $revertTransaction;
    }
}