<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Auth;
use Speakeasy\Serializer\Annotation\SerializedName;
use Speakeasy\Serializer\Annotation\SkipWhenNull;
use Speakeasy\Serializer\Annotation\Type;


class ListUsersResponse
{
    /**
     * $data
     *
     * @var ?array<User> $data
     */
    #[SerializedName('data')]
    #[Type('array<\formance\stack\Models\Auth\User>|null')]
    #[SkipWhenNull]
    public ?array $data = null;

    /**
     * @param  ?array<User>  $data
     * @phpstan-pure
     */
    public function __construct(?array $data = null)
    {
        $this->data = $data;
    }
}