<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Auth;


class ReadUserResponse
{
    /**
     *
     * @var ?User $user
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\formance\stack\Models\Auth\User|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?User $user = null;

    /**
     * @param  ?User  $user
     * @phpstan-pure
     */
    public function __construct(?User $user = null)
    {
        $this->user = $user;
    }
}